const services = [
    { href: '/metal-fabrication', title: 'Metal fabrication', text: 'Custom metal parts made from CAD models and engineering drawings.' },
    { href: '/3d-design-printing', title: '3D design and printing', text: 'CAD design and printed parts for prototypes, enclosures and fixtures.' },
    { href: '/electronics-prototyping', title: 'Electronics and automation', text: 'Sensors, data collection and controls for experiments and prototypes.' },
]

export const researchServices = {
    hub: {
        path: '/research-fabrication',
        title: 'Research Fabrication & Prototyping Singapore | FIT',
        description: 'Metal fabrication, CAD design, 3D printing and electronics for research and commercial projects in Singapore. Send FIT your drawings for a quotation.',
        eyebrow: 'Research and commercial projects',
        heading: 'Custom parts and prototypes',
        intro: 'We help research and engineering teams in Singapore with custom parts, prototypes and electronics. Send us your drawings or explain what you need to build.',
        sectionTitle: 'Our services',
        sectionIntro: 'Choose a service below. Projects that need both mechanical parts and electronics can be handled in one enquiry.',
        services,
        examplesTitle: 'Project examples',
        examples: [
            { title: 'Research fixtures', text: 'Sample holders, sensor mounts and fixtures that fit your experimental setup.' },
            { title: 'Product prototypes', text: 'Enclosures, brackets and assemblies for checking dimensions, fit and function.' },
            { title: 'Custom automation', text: 'Sensor readings, data logging and controls for a mechanism or experiment.' },
        ],
        audience: 'We welcome enquiries from research groups at Nanyang Technological University (NTU), the National University of Singapore (NUS), and other institutions, as well as commercial engineering teams in Singapore.',
        checklist: ['What you need to make and how it will be used', 'Drawings, CAD files, sketches or photographs', 'Quantity, key dimensions and operating conditions', 'Required date and budget, if available'],
        faqs: [
            { question: 'Do I need a finished CAD model?', answer: 'No. A sketch with dimensions is a useful starting point. We can quote for the design work as well as the parts.' },
            { question: 'Can you help with both parts and electronics?', answer: 'Yes. Include the mechanical and electrical requirements in your enquiry, along with any existing equipment. We’ll let you know what we can provide and what it will cost.' },
        ],
        enquirySubject: 'Research or commercial fabrication enquiry',
        enquiryFields: ['Organisation / research group:', 'Project and intended use:', 'Service needed:', 'Quantity and key dimensions:', 'Operating requirements:', 'Required date:', 'Budget (if available):', 'Files available (please attach to this email):'],
    },
    metal: {
        path: '/metal-fabrication',
        title: 'Custom Metal Fabrication Singapore | CAD & Drawings | FIT',
        description: 'Custom metal parts made from CAD models and engineering drawings using conventional metalworking. Fabrication for research and business in Singapore.',
        eyebrow: 'Fabrication services',
        heading: 'Metal fabrication',
        intro: 'We supply custom metal parts made from your 3D CAD model or engineering drawing using conventional metalworking. Typical lead time is 2–6 weeks; we’ll confirm a delivery date with your quote.',
        sectionTitle: 'Parts made from your drawings',
        sectionIntro: 'Send the part dimensions, material and quantity. Mark any critical tolerances, holes, threads and surfaces that need to fit another part.',
        examplesTitle: 'Part examples',
        examples: [
            { title: 'Brackets and mounting plates', text: 'Supports and adapters with mounting holes to suit your equipment.' },
            { title: 'Sample holders and fixtures', text: 'Parts for holding and positioning samples during an experiment.' },
            { title: 'Housings and assembly parts', text: 'Custom housings and components for a prototype or mechanical assembly.' },
        ],
        checklist: ['STEP or another CAD file, plus a dimensioned PDF drawing where possible', 'Material type or grade, quantity and intended use', 'Critical dimensions, tolerances, threads and mating interfaces', 'Surface finish, operating conditions and required delivery date'],
        faqs: [
            { question: 'Can you work from a sketch?', answer: 'Send the sketch with dimensions and explain how the part will be used. Any CAD design or drawing work will be priced separately.' },
            { question: 'Which metals and fabrication methods are available?', answer: 'Tell us the material grade and features you need. We’ll confirm the available material, fabrication method and finish before quoting.' },
            { question: 'Is an STL file enough?', answer: 'An STL shows the shape, but manufacturing tolerances and thread specifications should be supplied in a drawing. Include a STEP file if available.' },
        ],
        enquirySubject: 'Custom metal fabrication enquiry',
        enquiryFields: ['Organisation:', 'Part and intended use:', 'Quantity:', 'Material / grade:', 'Critical dimensions and tolerances:', 'Finish and operating conditions:', 'Required date:', 'CAD / drawing files (please attach to this email):'],
    },
    design: {
        path: '/3d-design-printing',
        title: '3D Design & Printing Services Singapore | CAD Prototypes | FIT',
        description: 'CAD design and 3D printing in Singapore for prototypes, enclosures and research fixtures. Send a sketch, measurements or an existing model.',
        eyebrow: 'Fabrication services',
        heading: '3D design and printing',
        intro: 'We design and print custom parts from sketches, measurements or existing CAD files. Use a printed prototype to check the size, fit and layout before making further changes.',
        sectionTitle: 'Design help and printed parts',
        sectionIntro: 'You can request CAD design, printed parts or both. Tell us how the part will be used, including any loads, heat or outdoor exposure, so we can suggest a suitable material.',
        examplesTitle: 'Part examples',
        examples: [
            { title: 'Electronics enclosures', text: 'Cases with board mounts, connector openings and access to controls.' },
            { title: 'Jigs and positioning aids', text: 'Parts that locate, support or align a component during an experiment or assembly.' },
            { title: 'Prototype assemblies', text: 'Related parts for testing fit, clearances and access before the next version.' },
        ],
        checklist: ['A sketch, reference images or an existing CAD model', 'Overall dimensions, mating parts and required clearances', 'Quantity, intended use, loading and operating environment', 'Required date and whether you need CAD files, printed parts or both'],
        faqs: [
            { question: 'I already have a printable model. How do I order?', answer: 'Upload it on the print request page to see the available options. Email us first if the design needs changes.' },
            { question: 'Will I receive the CAD files?', answer: 'Tell us which editable and export formats you need. Your quotation will list the files, usage rights and number of revisions included.' },
            { question: 'Can the final part be made in metal?', answer: 'Let us know from the start. A printed prototype may need design changes for conventional metal fabrication, which is quoted separately.' },
        ],
        printLink: true,
        enquirySubject: '3D design and printing enquiry',
        enquiryFields: ['Organisation / name:', 'Part and intended use:', 'Dimensions and mating components:', 'Quantity:', 'Loading and operating environment:', 'CAD files, printed parts or both:', 'Required date:', 'Sketches / CAD files (please attach to this email):'],
    },
    electronics: {
        path: '/electronics-prototyping',
        title: 'Custom Electronics & Automation Prototyping Singapore | FIT',
        description: 'Electronics for research and automation prototypes in Singapore. Get help connecting sensors, collecting data and controlling custom mechanisms.',
        eyebrow: 'Prototyping services',
        heading: 'Electronics and automation',
        intro: 'We help connect sensors, collect readings and control mechanisms for research setups and prototypes. Send us the equipment details and explain what you want the system to do.',
        sectionTitle: 'Electronics for your setup',
        sectionIntro: 'A simple sketch or block diagram helps us understand the connections. Include the sensors, power supply and controller you already have, plus any software the setup needs to work with.',
        examplesTitle: 'Project examples',
        examples: [
            { title: 'Sensors and data collection', text: 'Connections and data logging for recording or displaying sensor readings.' },
            { title: 'Controls and automation', text: 'Control sequences that operate a mechanism or respond to a sensor input.' },
            { title: 'Enclosures and mounting', text: 'Board mounts, connectors and cable access within a custom part or enclosure.' },
        ],
        checklist: ['What the system needs to do, with a sketch or block diagram', 'Model numbers for existing sensors, controllers, actuators and equipment', 'Power supplies, signal levels, communication interfaces and physical constraints', 'Required accuracy, sampling rate, operating environment and acceptance checks', 'Software or file requirements, quantity and required date'],
        faqs: [
            { question: 'Can you use equipment we already have?', answer: 'Send the model numbers, manuals and interface details. We’ll check compatibility before quoting.' },
            { question: 'Can you provide the enclosure or mounting parts too?', answer: 'Yes. Include the dimensions and mechanical requirements so we can price the parts and electronics together.' },
            { question: 'What will we receive at handover?', answer: 'The quotation will list the hardware, software, documentation and functional tests included. Tell us if you need connection diagrams or source files to maintain the setup.' },
        ],
        enquirySubject: 'Research electronics and automation enquiry',
        enquiryFields: ['Organisation / research group:', 'Required behaviour:', 'Existing equipment and model numbers:', 'Sensors / inputs:', 'Actuators / outputs:', 'Power and communication interfaces:', 'Physical constraints and operating environment:', 'Acceptance checks and handover needs:', 'Required date:'],
    },
}

export const serviceLinks = services
