const services = [
    { href: '/metal-fabrication', title: 'Metal fabrication', text: 'Custom metal parts made from CAD models or drawings using conventional metalworking. Typical lead time: 2–6 weeks, confirmed in your quotation.' },
    { href: '/3d-design-printing', title: '3D design and printing', text: 'Turn a sketch or set of dimensions into a 3D design, then make and refine a printed prototype.' },
    { href: '/electronics-prototyping', title: 'Electronics and automation', text: 'Bring sensors, controls and custom parts together for a research setup or automation prototype.' },
]

export const researchServices = {
    hub: {
        path: '/research-fabrication',
        title: 'Research Fabrication & Prototyping Singapore | FIT',
        description: 'Custom metal fabrication, CAD design, 3D printing and electronics integration for research and commercial projects in Singapore. Send FIT your project brief.',
        eyebrow: 'Research & commercial projects · Singapore',
        heading: 'Fabrication for research and business.',
        intro: 'Get help making the parts and electronics your project needs. FIT supports research and commercial enquiries, from a single custom bracket to a prototype with sensors and controls.',
        briefTitle: 'What are you building?',
        brief: ['A metal part from a drawing', 'A 3D design or printed prototype', 'An experimental setup with electronics'],
        note: 'Share the intended use, dimensions and required date. We’ll review the scope before quoting.',
        sectionTitle: 'Fabrication and prototyping for research',
        sectionIntro: 'Choose the service that fits your starting point. If your project combines mechanical parts and electronics, include both in one enquiry so the interfaces can be reviewed together.',
        services,
        examplesTitle: 'Start with the problem you need to solve',
        examples: [
            { title: 'Research fixtures', text: 'Discuss a sample holder, sensor mount or experimental fixture. Include the equipment it connects to and the dimensions that matter.' },
            { title: 'Product prototypes', text: 'Explore an enclosure, bracket or assembly before committing to a larger batch. Explain what the prototype needs to demonstrate.' },
            { title: 'Custom automation', text: 'Describe the action you want to automate, the signals available and the parts that need to move or be measured.' },
        ],
        audience: 'We welcome enquiries from research groups at Nanyang Technological University (NTU), the National University of Singapore (NUS), and other institutions, as well as commercial engineering teams in Singapore.',
        checklist: ['A short explanation of the project and intended use', 'Available drawings, CAD files, sketches or photographs of the part', 'Quantity, key dimensions and operating requirements', 'Your required date and an indicative budget, if available'],
        steps: [
            { title: 'Share your brief', text: 'Send the available design information and explain what the part or system needs to do.' },
            { title: 'Agree the scope', text: 'We review the design work, fabrication requirements, deliverables and schedule with you before proceeding.' },
            { title: 'Make and check', text: 'Fabrication and integration follow the agreed scope. Inspection and functional checks are defined for the project.' },
        ],
        faqs: [
            { question: 'Can I enquire without a finished CAD model?', answer: 'Yes. Send a sketch, dimensions and the intended use. If design work is needed, its scope and fee will be agreed before fabrication.' },
            { question: 'Can a project include both parts and electronics?', answer: 'Yes. Describe the mechanical and electrical requirements together, including mounting points, power, interfaces and the behaviour you need. Feasibility and the work included are confirmed during review.' },
            { question: 'How long does metal fabrication take?', answer: 'Typical lead time is 2–6 weeks. Timing depends on the drawings, materials, quantity and finishing requirements. Your quotation will confirm the schedule and when the lead time begins.' },
        ],
        enquirySubject: 'Research or commercial fabrication enquiry',
        enquiryFields: ['Organisation / research group:', 'Project and intended use:', 'Service needed:', 'Quantity and key dimensions:', 'Operating requirements:', 'Required date:', 'Budget (if available):', 'Files available (please attach to this email):'],
    },
    metal: {
        path: '/metal-fabrication',
        title: 'Custom Metal Fabrication Singapore | CAD & Drawings | FIT',
        description: 'Custom metal parts made from CAD models and engineering drawings using conventional metalworking. Research and commercial enquiries. Typical lead time 2–6 weeks.',
        eyebrow: 'Metal fabrication · Singapore',
        heading: 'Metal parts made to your design.',
        intro: 'Send your 3D CAD model, engineering drawing or dimensioned design for custom metal fabrication. We review the part requirements and arrange conventional metalworking to suit the agreed specification.',
        briefTitle: 'Typical lead time',
        highlight: '2–6 weeks',
        brief: ['Research and commercial projects', 'CAD models and engineering drawings', 'Process and finish agreed before fabrication'],
        note: 'Timing is confirmed after reviewing the drawings, material requirements and quantity. The quotation states when the lead time begins.',
        sectionTitle: 'Custom metal fabrication for research and industry',
        sectionIntro: 'A useful drawing explains more than the outside shape. Let us know which surfaces locate the part, what it connects to, and which dimensions are critical. The fabrication method is reviewed against those requirements.',
        examplesTitle: 'Parts you can discuss with us',
        examples: [
            { title: 'Brackets and mounting plates', text: 'Share the mounting pattern, loads, available space and mating components for a custom support or adapter.' },
            { title: 'Sample holders and fixtures', text: 'Explain how the sample is held, positioned and accessed, including any temperature or chemical exposure.' },
            { title: 'Housings and assembly parts', text: 'Provide the assembly layout, access requirements, holes, threads and finish needed for the finished part.' },
        ],
        checklist: ['STEP or another available CAD format, plus a dimensioned PDF drawing where possible', 'Material type or grade, quantity and intended use', 'Critical dimensions, tolerances, threads and mating interfaces', 'Surface finish, operating conditions and required delivery date'],
        steps: [
            { title: 'Review the design', text: 'We clarify the dimensions, material, finish and any missing information needed for fabrication.' },
            { title: 'Confirm the quotation', text: 'Agree the fabrication scope, price and delivery schedule. Design changes may affect both cost and timing.' },
            { title: 'Fabricate to the agreed scope', text: 'Parts are made using the agreed conventional metalworking route, with inspection requirements defined in the quotation.' },
        ],
        faqs: [
            { question: 'Can you work from a 3D model or a sketch?', answer: 'A 3D CAD model is a useful starting point. Add a dimensioned drawing for critical tolerances, threads and finishes. If you only have a sketch, we can review the design work needed and quote that scope separately.' },
            { question: 'Which metals and fabrication methods are available?', answer: 'Tell us the material grade and features your design needs. We confirm the available material, fabrication route and finishing options after reviewing the part, rather than assuming every combination is suitable.' },
            { question: 'Is an STL file enough to request a quotation?', answer: 'It can help explain the shape, but may not contain the dimensions and tolerances needed for metal fabrication. Include the overall size, a dimensioned drawing and a STEP file if available.' },
            { question: 'When will my parts be ready?', answer: 'Typical lead time is 2–6 weeks, subject to material, fabrication, quantity and finishing requirements. We confirm the delivery schedule and its starting point in the quotation.' },
        ],
        enquirySubject: 'Custom metal fabrication enquiry',
        enquiryFields: ['Organisation:', 'Part and intended use:', 'Quantity:', 'Material / grade:', 'Critical dimensions and tolerances:', 'Finish and operating conditions:', 'Required date:', 'CAD / drawing files (please attach to this email):'],
    },
    design: {
        path: '/3d-design-printing',
        title: '3D Design & Printing Services Singapore | CAD Prototypes | FIT',
        description: 'Turn sketches and dimensions into CAD designs and 3D printed prototypes in Singapore. Design support for custom enclosures, fixtures and research parts.',
        eyebrow: '3D design & printing · Singapore',
        heading: '3D design, from sketch to printed part.',
        intro: 'Get help turning your idea or dimensions into a 3D design, then use a printed prototype to check the fit and develop the part. Share what it needs to do, not just how it should look.',
        briefTitle: 'Start at any stage',
        brief: ['A sketch with measurements', 'An existing CAD model to develop', 'A printable model ready for a quote'],
        note: 'Design work, revisions, print material and deliverables are agreed for each project.',
        sectionTitle: '3D design through to a printed prototype',
        sectionIntro: 'A prototype helps you check access, mounting points and how parts fit together. Tell us about forces, temperature and the environment so those requirements can inform the design and material review.',
        examplesTitle: 'Useful starting projects',
        examples: [
            { title: 'Electronics enclosures', text: 'Plan board mounts, connector openings and access to controls around the actual components you intend to use.' },
            { title: 'Jigs and positioning aids', text: 'Develop a part that helps locate, support or align a component during an experiment or assembly task.' },
            { title: 'Prototype assemblies', text: 'Check the size and fit of related parts, then agree any changes before the next version is made.' },
        ],
        checklist: ['A sketch, reference images or existing CAD model', 'Overall dimensions, mating parts and required clearances', 'Quantity, intended use, loading and operating environment', 'Required date and whether you need CAD files, printed parts or both'],
        steps: [
            { title: 'Define the part', text: 'Explain the function and constraints. We agree the design scope, file deliverables and revisions included.' },
            { title: 'Review the model', text: 'Check key dimensions and interfaces before printing. Material and print requirements are reviewed for the intended use.' },
            { title: 'Try the prototype', text: 'Use the printed part to check the agreed requirements. Further design iterations are scoped before additional work.' },
        ],
        faqs: [
            { question: 'Can you design a part from my sketch?', answer: 'Yes. Include measurements and explain how the part will be used. We review the information and agree the design work and fee before starting.' },
            { question: 'I already have a printable model. What should I do?', answer: 'Use the print request page to upload your model and review the available print options. If you need design changes or help choosing a material, send an enquiry first.' },
            { question: 'Will I receive the CAD files?', answer: 'Tell us which editable and export formats you need. File deliverables, usage rights and the revisions included should be agreed in the quotation.' },
            { question: 'Can the final part be made in metal?', answer: 'If the intended final part needs metal fabrication, include that requirement from the start. The design will need a separate review for conventional metalworking, with its own quotation and schedule.' },
        ],
        printLink: true,
        enquirySubject: '3D design and printing enquiry',
        enquiryFields: ['Organisation / name:', 'Part and intended use:', 'Dimensions and mating components:', 'Quantity:', 'Loading and operating environment:', 'CAD files, printed parts or both:', 'Required date:', 'Sketches / CAD files (please attach to this email):'],
    },
    electronics: {
        path: '/electronics-prototyping',
        title: 'Custom Electronics & Automation Prototyping Singapore | FIT',
        description: 'Electronics integration for research setups and custom automation prototypes in Singapore. Discuss sensors, controls, data collection and mechanical interfaces.',
        eyebrow: 'Electronics & automation · Singapore',
        heading: 'Electronics for research and automation.',
        intro: 'Bring electronics into a custom part or experimental setup. Discuss sensor integration, data collection and control functions for a research project or automation prototype.',
        briefTitle: 'Tell us what needs to happen',
        brief: ['What should be measured?', 'What should move or switch?', 'Where should the data go?'],
        note: 'Hardware, software, mechanical interfaces and testing are scoped after a technical review.',
        sectionTitle: 'Electronics integration for custom parts',
        sectionIntro: 'Describe the behaviour you need and the equipment you already have. We review how the sensors, controller, power supply and mechanical parts need to work together before agreeing the implementation.',
        examplesTitle: 'Research and automation enquiries',
        examples: [
            { title: 'Sensor and data collection setups', text: 'Discuss the quantity to measure, sensor signals, sampling needs and how you want to record or view the readings.' },
            { title: 'Controls and simple automation', text: 'Describe the sequence, inputs and outputs for a prototype that operates a mechanism or responds to a measured condition.' },
            { title: 'Electronics inside custom parts', text: 'Plan mounting, connectors, cable access and enclosure space so the mechanical design suits the chosen electronics.' },
        ],
        checklist: ['A description of the required behaviour and a sketch or block diagram', 'Existing sensors, controllers, actuators and equipment model numbers', 'Power supplies, signal levels, communication interfaces and physical constraints', 'Required accuracy, sampling rate, operating environment and acceptance checks', 'Software or file deliverables, quantity and required date'],
        steps: [
            { title: 'Define the behaviour', text: 'Agree the inputs, outputs and operating sequence, plus what a successful demonstration should show.' },
            { title: 'Plan the interfaces', text: 'Review hardware compatibility, connections, mounting and software needs. Confirm the parts and work included in the quotation.' },
            { title: 'Integrate and test', text: 'Build to the agreed scope and check the specified functions. Documentation and handover requirements are set for the project.' },
        ],
        faqs: [
            { question: 'Can you work with equipment we already have?', answer: 'Send the model numbers, manuals and available interface details. We first review compatibility and what can be accessed or controlled.' },
            { question: 'Can you provide the enclosure or mounting parts too?', answer: 'Include the mechanical requirements in the same enquiry. We can review 3D design, printing or metal fabrication alongside the electronics so the interfaces are considered together.' },
            { question: 'What is included in testing and handover?', answer: 'The quotation defines the functions to check and the deliverables, which may include connection diagrams, operating notes or source files where agreed. Tell us what your team needs to maintain the setup.' },
            { question: 'How long will an electronics project take?', answer: 'Timing depends on the design work, component availability, integration and testing scope. We confirm a project schedule after reviewing your requirements.' },
        ],
        enquirySubject: 'Research electronics and automation enquiry',
        enquiryFields: ['Organisation / research group:', 'Required behaviour:', 'Existing equipment and model numbers:', 'Sensors / inputs:', 'Actuators / outputs:', 'Power and communication interfaces:', 'Physical constraints and operating environment:', 'Acceptance checks and handover needs:', 'Required date:'],
    },
}

export const serviceLinks = services
