'use client'
import Link from 'next/link'
import { SignInButton, useUser } from '@clerk/nextjs'
import { useState } from 'react'
import CommunityEditor from './CommunityEditor'
import CommunityReport from './CommunityReport'
import { topicLabels, useCommunityPage } from './communityClient'
import styles from './Community.module.css'
export default function CommunityThread({ entryId }) {
  const { isLoaded, isSignedIn, user } = useUser()
  const [cursor, setCursor] = useState(''), [editingFor, setEditingFor] = useState(null), [notice, setNotice] = useState('')
  const page = useCommunityPage(`/api/community/${entryId}${cursor ? `?cursor=${encodeURIComponent(cursor)}` : ''}`)
  const signedIn = Boolean(isLoaded && isSignedIn && user?.id), entry = page.data?.entry
  return <div className={`${styles.shell} ph-mask ph-no-capture`}><nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/community">Community</Link><span>/</span><span aria-current="page">Discussion</span></nav>{page.loading && <p role="status">Loading discussion…</p>}{page.error && <div role="alert"><h1>Discussion unavailable</h1><p>{page.error}</p><button onClick={page.reload}>Try again</button></div>}{entry && <><article className={styles.thread}><p className={styles.eyebrow}>{entry.kind === 'project' ? 'Project' : 'Question'} · {topicLabels[entry.topic]}</p><h1>{entry.title}</h1><p className={styles.meta}>By {entry.displayName}</p><p className={styles.body}>{entry.body}</p>{signedIn && <CommunityReport key={`${user.id}:${entry.revision}`} entry={entry} />}</article><section aria-labelledby="community-comments"><h2 id="community-comments">Discussion</h2>{page.data.comments.length === 0 && <p>No published comments on this page. Comments appear after moderator approval.</p>}{page.data.comments.map(comment => <article key={comment.entryId} className={styles.card}><p className={styles.meta}>{comment.displayName}</p><p className={styles.body}>{comment.body}</p>{signedIn && <CommunityReport key={`${user.id}:${comment.revision}`} entry={comment} />}</article>)}<div className={styles.actions}>{cursor && <button className={styles.secondary} onClick={() => setCursor('')}>Newest comments</button>}{page.data.nextCursor && <button className={styles.secondary} onClick={() => setCursor(page.data.nextCursor)}>Older comments</button>}</div></section>{notice && <p role="status" className={styles.notice}>{notice}</p>}{signedIn ? editingFor === user.id ? <CommunityEditor key={user.id} parentId={entryId} onCancel={() => setEditingFor(null)} onSaved={() => { setEditingFor(null); setNotice('Comment saved for review. Check My submissions for its status.'); page.reload() }} /> : <button onClick={() => { setEditingFor(user.id); setNotice('') }}>Add a comment</button> : <SignInButton mode="modal" forceRedirectUrl={`/community/${entryId}`} signUpForceRedirectUrl={`/community/${entryId}`}><button disabled={!isLoaded}>Sign in to comment or report</button></SignInButton>}<p className={styles.help}>All comments and edits need approval. Do not include private or student information. <Link href="/community">Community guidelines and My submissions</Link></p></>}</div>
}
