yarnPath: .yarn/releases/yarn-4.12.0.cjs

# Explicit npm registry so tools that call `yarn config get registry`
# can resolve a value and patch lockfiles (e.g. Next.js SWC helpers).
npmRegistryServer: "https://registry.npmjs.org"

# Allow Yarn to update the lockfile in CI (e.g. on Vercel)
# instead of failing when it detects that it would modify it.
enableImmutableInstalls: false
