import Link from 'next/link'
import { buildPageMetadata } from '@/lib/seo/metadata'
import styles from './PrintingProblems.module.css'

export const metadata = buildPageMetadata({ title: 'Common 3D Printing Problems | FIT', description: 'Recognise nozzle blobs, first-layer problems, under-extrusion and stringing. Find safe next steps and model-specific manufacturer guidance.', path: '/guides/3d-printing-problems' })

export default function PrintingProblems() {
  return <main className={styles.page}>
    <nav aria-label="Breadcrumb"><Link href="/maker-tools">Maker Tools</Link><span>/</span><span aria-current="page">Printing problems</span></nav>
    <header><p className={styles.eyebrow}>THE MAKER FIELD GUIDE</p><h1>A failed print is a clue.</h1><p>Start with what you can see. These common symptoms help you describe a problem and choose the right next step; they do not establish a diagnosis.</p></header>
    <aside className={styles.notice}><h2>Before you troubleshoot</h2><p>Stop a failed print using the printer controls. Keep clear of moving parts and hot surfaces. If plastic surrounds wiring, parts are damaged, or you are unsure, stop work and request an assessment. Do not pull hardened plastic from the hotend or improvise a heating or disassembly procedure.</p><p>Record the exact printer model, material, slicer profile, error message and when the failure began. Follow the manufacturer instructions for that model.</p></aside>
    <nav className={styles.topics} aria-label="Choose a printing problem"><a href="#nozzle-blob">Nozzle blob</a><a href="#first-layer">First-layer lifting</a><a href="#under-extrusion">Clicking or thin lines</a><a href="#stringing">Stringing</a></nav>
    <section id="nozzle-blob"><p className={styles.number}>01 / THE PRINT BECAME A MASS</p><h2>Plastic collected around the nozzle</h2><dl><dt>What you may see</dt><dd>A lump of plastic surrounding the nozzle or hotend, rather than the intended part.</dd><dt>What it can mean</dt><dd>Prusa describes one common sequence: a first layer detaches, catches on the nozzle, and more material accumulates. The visible blob alone does not identify every cause.</dd><dt>Next step</dt><dd>Stop the print and photograph the condition without touching it. Heater and temperature-sensor wires can be fragile. Use the exact model procedure or ask for an assessment before attempting removal.</dd></dl><p className={styles.source}>Manufacturer reference: <a href="https://help.prusa3d.com/article/extruder-blob_2005">Prusa: Extruder blob</a>. Check the supported printer list and instructions for your model.</p></section>
    <section id="first-layer"><p className={styles.number}>02 / THE FOUNDATION LIFTS</p><h2>The first layer will not stay on the plate</h2><dl><dt>What you may see</dt><dd>Loose first-layer lines, lifting edges, or a part moving with the nozzle.</dd><dt>What it can mean</dt><dd>Surface preparation and first-layer setup can affect adhesion. The correct treatment depends on the build plate, material and printer.</dd><dt>Next step</dt><dd>Confirm the selected plate, material and printer profile. Follow the relevant cleaning and first-layer calibration instructions. Do not apply a universal solvent or temperature recommendation: textured, satin and smooth plates have different care requirements.</dd></dl><p className={styles.source}>Manufacturer reference: <a href="https://help.prusa3d.com/article/first-layer-issues_1804">Prusa: First layer issues</a>. Plate and material guidance is specific to the combinations described there.</p></section>
    <section id="under-extrusion"><p className={styles.number}>03 / THE FLOW IS INTERRUPTED</p><h2>Clicking, missing material or very thin lines</h2><dl><dt>What you may see</dt><dd>Little or no extrusion, incomplete lines, or clicking from the extruder while it tries to feed.</dd><dt>What it can mean</dt><dd>Resistance or a partial blockage can occur along the filament path. A nozzle replacement alone may not address the cause.</dd><dt>Next step</dt><dd>Record whether the symptom begins during loading or printing, and any displayed error. Use the filament-path troubleshooting instructions for your model. Avoid forcing filament or opening a hot assembly without the relevant procedure.</dd></dl><p className={styles.source}>Model-specific example: <a href="https://help.prusa3d.com/article/clogged-nozzle-hotend-mk3-5-s-mk3s-mk2-5s_2008">Prusa: Clogged nozzle/hotend for MK3.5/S, MK3S+ and MK2.5S</a>. This is not a disassembly guide for other printers.</p></section>
    <section id="stringing"><p className={styles.number}>04 / THREADS BETWEEN FEATURES</p><h2>Fine strings stretch across gaps</h2><dl><dt>What you may see</dt><dd>Thin strands between separate areas of the printed part.</dd><dt>What it can mean</dt><dd>Filament can ooze during travel moves. Temperature, retraction settings and material left on the nozzle are among the factors discussed by Prusa.</dd><dt>Next step</dt><dd>Begin with the manufacturer profile for your printer and material, record changes, and follow its troubleshooting sequence. Avoid changing several settings at once or copying temperatures from another printer.</dd></dl><p className={styles.source}>Manufacturer reference: <a href="https://help.prusa3d.com/article/stringing-and-oozing_1805">Prusa: Stringing and oozing</a>. Use settings only within your own printer and material guidance.</p></section>
    <footer><h2>Bring the symptoms, not a guess.</h2><p>For another brand or an uncertain fault, use its exact model manual or send FIT the printer details and observations. Assessment comes before a repair quote.</p><div className={styles.actions}><Link href="/printer-repair">Request a printer assessment</Link><Link href="/community">Ask the maker community</Link><Link href="/maker-tools">Back to Maker Tools</Link></div><p className={styles.source}>Manufacturer references reviewed 9 October 2026. General orientation only; model instructions take precedence.</p></footer>
  </main>
}
