export const supportedCountries = [
    { name: "Albania", code: "AL", currency: "ALL", bankAccountFormat: "ALkk BBBB CCCC CCCC CCCC CCCC CCCC" },
    { name: "Antigua & Barbuda", code: "AG", currency: "XCD", bankAccountFormat: "AGkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Argentina", code: "AR", currency: "ARS", bankAccountFormat: "ARkk BBBB CCCC CCCC CCCC XXXXX" },
    { name: "Armenia", code: "AM", currency: "AMD", bankAccountFormat: "AMkk BBBB CCCC CCCC CCCC CCCC CCCC" },
    { name: "Australia", code: "AU", currency: "AUD", bankAccountFormat: "XXX-XXX XXXXXX" },
    { name: "Austria", code: "AT", currency: "EUR", bankAccountFormat: "ATkk XXXX XXXX XXXX XXXX" },
    { name: "Bahamas", code: "BS", currency: "BSD", bankAccountFormat: "BSkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Bahrain", code: "BH", currency: "BHD", bankAccountFormat: "BHkk BBBB CCCC CCCC CCCC CC" },
    { name: "Belgium", code: "BE", currency: "EUR", bankAccountFormat: "BEkk XXXX XXXX XXXX" },
    { name: "Benin", code: "BJ", currency: "XOF", bankAccountFormat: "BJkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Bolivia", code: "BO", currency: "BOB", bankAccountFormat: "BOkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Bosnia & Herzegovina", code: "BA", currency: "BAM", bankAccountFormat: "BAkk BBCC CCCC CCCC CCCC" },
    { name: "Botswana", code: "BW", currency: "BWP", bankAccountFormat: "BWkk BBBB CCCC CCCC CCCC C" },
    { name: "Brunei", code: "BN", currency: "BND", bankAccountFormat: "BNkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Bulgaria", code: "BG", currency: "BGN", bankAccountFormat: "BGkk BBBB SSSS HHCC CCCC" },
    { name: "Cambodia", code: "KH", currency: "KHR", bankAccountFormat: "KHkk BBBB CCCC CCCC CCCC" },
    { name: "Canada", code: "CA", currency: "CAD", bankAccountFormat: "XXXXX-YYYYYYYYYY" },
    { name: "Chile", code: "CL", currency: "CLP", bankAccountFormat: "CLkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Colombia", code: "CO", currency: "COP", bankAccountFormat: "COkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Costa Rica", code: "CR", currency: "CRC", bankAccountFormat: "CRkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Côte d’Ivoire", code: "CI", currency: "XOF", bankAccountFormat: "CIkk BBBB CCCC CCCC CCCC CCCC CCCC" },
    { name: "Cyprus", code: "CY", currency: "EUR", bankAccountFormat: "CYkk BBBB SSSS CCCC CCCC CCCC" },
    { name: "Czech Republic", code: "CZ", currency: "CZK", bankAccountFormat: "CZkk BBBB BBBB CCCC CCCC CCCC" },
    { name: "Denmark", code: "DK", currency: "DKK", bankAccountFormat: "DKkk BBBB CCCC CCCC CC" },
    { name: "Dominican Republic", code: "DO", currency: "DOP", bankAccountFormat: "DOkk BBBB CCCC CCCC CCCC CCCC CCCC" },
    { name: "Ecuador", code: "EC", currency: "USD", bankAccountFormat: "ECkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Egypt", code: "EG", currency: "EGP", bankAccountFormat: "EGkk BBBB SCCC CCCC CCCC CCCC CCCC" },
    { name: "El Salvador", code: "SV", currency: "USD", bankAccountFormat: "SVkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Estonia", code: "EE", currency: "EUR", bankAccountFormat: "EEkk BBBB CCCC CCCC CCCC" },
    { name: "Ethiopia", code: "ET", currency: "ETB", bankAccountFormat: "ETkk BBBB CCCC CCCC CCCC" },
    { name: "Finland", code: "FI", currency: "EUR", bankAccountFormat: "FIkk BBBB BBCC CCCC CC" },
    { name: "France", code: "FR", currency: "EUR", bankAccountFormat: "FRkk BBBB BGGG GGCC CCCC CCCC CKK" },
    { name: "Gambia", code: "GM", currency: "GMD", bankAccountFormat: "GMkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Germany", code: "DE", currency: "EUR", bankAccountFormat: "DEkk BBBB BBBB CCCC CCCC CC" },
    { name: "Ghana", code: "GH", currency: "GHS", bankAccountFormat: "GHkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Greece", code: "GR", currency: "EUR", bankAccountFormat: "GRkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Guatemala", code: "GT", currency: "GTQ", bankAccountFormat: "GTkk BBBB CCCC CCCC CCCC CCCC CCCC" },
    { name: "Guyana", code: "GY", currency: "GYD", bankAccountFormat: "GYkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Hong Kong", code: "HK", currency: "HKD", bankAccountFormat: "BBBB-AAAAAAA-CC" },
    { name: "Hungary", code: "HU", currency: "HUF", bankAccountFormat: "HUkk BBBB BBCC CCCC CCCC CCCC CCCC" },
    { name: "Iceland", code: "IS", currency: "ISK", bankAccountFormat: "ISkk BBBB CCCC CCCC XXXX" },
    { name: "Ireland", code: "IE", currency: "EUR", bankAccountFormat: "IEkk AAAA BBBB BBCC CCCC CC" },
    { name: "Israel", code: "IL", currency: "ILS", bankAccountFormat: "ILkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Italy", code: "IT", currency: "EUR", bankAccountFormat: "ITkk XBBB BBCC CCCC CCCC CCCC CCC" },
    { name: "Jamaica", code: "JM", currency: "JMD", bankAccountFormat: "JMkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Japan", code: "JP", currency: "JPY", bankAccountFormat: "XXXX-YYYYYYYYY" },
    { name: "Jordan", code: "JO", currency: "JOD", bankAccountFormat: "JOkk BBBB CCCC CCCC CCCC CCCC CCC" },
    { name: "Kenya", code: "KE", currency: "KES", bankAccountFormat: "XXXXXYYYYYYYYYY" },
    { name: "Kuwait", code: "KW", currency: "KWD", bankAccountFormat: "KWkk BBBB CCCC CCCC CCCC CCCC CCCC" },
    { name: "Latvia", code: "LV", currency: "EUR", bankAccountFormat: "LVkk BBBB CCCC CCCC CCCC C" },
    { name: "Lithuania", code: "LT", currency: "EUR", bankAccountFormat: "LTkk BBBB BCCC CCCC CCCC" },
    { name: "Luxembourg", code: "LU", currency: "EUR", bankAccountFormat: "LUkk BBCC CCCC CCCC CCCC" },
    { name: "Macao SAR China", code: "MO", currency: "MOP", bankAccountFormat: "MOkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Madagascar", code: "MG", currency: "MGA", bankAccountFormat: "MGkk BBBB CCCC CCCC CCCC CCCC CCCC" },
    { name: "Malta", code: "MT", currency: "EUR", bankAccountFormat: "MTkk BBBB SSSS CCCC CCCC CCCC CCCC" },
    { name: "Mauritius", code: "MU", currency: "MUR", bankAccountFormat: "MUkk BBSS CCCC CCCC CCCC CCCC CCCC C" },
    { name: "Mexico", code: "MX", currency: "MXN", bankAccountFormat: "BBBBBSSSAAAAAAAA" },
    { name: "Moldova", code: "MD", currency: "MDL", bankAccountFormat: "MDkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Monaco", code: "MC", currency: "EUR", bankAccountFormat: "MCkk BBBB BGGG GGCC CCCC CCCC CKK" },
    { name: "Mongolia", code: "MN", currency: "MNT", bankAccountFormat: "MNkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Morocco", code: "MA", currency: "MAD", bankAccountFormat: "MAkk BBBB CCCC CCCC CCCC CCCC CCCC" },
    { name: "Namibia", code: "NA", currency: "NAD", bankAccountFormat: "NAkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Netherlands", code: "NL", currency: "EUR", bankAccountFormat: "NLkk BBBB CCCC CCCC CC" },
    { name: "New Zealand", code: "NZ", currency: "NZD", bankAccountFormat: "BB-AAAA-CCCCCCC" },
    { name: "Nigeria", code: "NG", currency: "NGN", bankAccountFormat: "XXXXXXXXXX" },
    { name: "North Macedonia", code: "MK", currency: "MKD", bankAccountFormat: "MKkk BBBB CCCC CCCC CCCC" },
    { name: "Norway", code: "NO", currency: "NOK", bankAccountFormat: "NOkk BBBB CCCC CC" },
    { name: "Oman", code: "OM", currency: "OMR", bankAccountFormat: "OMkk BBBB CCCC CCCC CCCC CCCC CCC" },
    { name: "Pakistan", code: "PK", currency: "PKR", bankAccountFormat: "PKkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Panama", code: "PA", currency: "PAB", bankAccountFormat: "PAkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Paraguay", code: "PY", currency: "PYG", bankAccountFormat: "PYkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Peru", code: "PE", currency: "PEN", bankAccountFormat: "PEkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Philippines", code: "PH", currency: "PHP", bankAccountFormat: "PHkk BBBB CCCC CCCC CCCC CCCC CCCC" },
    { name: "Poland", code: "PL", currency: "PLN", bankAccountFormat: "PLkk BBBB BBBB CCCC CCCC CCCC CCCC" },
    { name: "Portugal", code: "PT", currency: "EUR", bankAccountFormat: "PTkk BBBB SSSS CCCC CCCC CCCC C" },
    { name: "Qatar", code: "QA", currency: "QAR", bankAccountFormat: "QAkk BBBB CCCC CCCC CCCC CCCC CCCC" },
    { name: "Romania", code: "RO", currency: "RON", bankAccountFormat: "ROkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Rwanda", code: "RW", currency: "RWF", bankAccountFormat: "RWkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Saudi Arabia", code: "SA", currency: "SAR", bankAccountFormat: "SAkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Senegal", code: "SN", currency: "XOF", bankAccountFormat: "SNkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Serbia", code: "RS", currency: "RSD", bankAccountFormat: "RSkk BBBB BCCC CCCC CCCC CCCC" },
    { name: "Singapore", code: "SG", currency: "SGD", bankAccountFormat: "BBBB-AAA-CCCCCCC" },
    { name: "Slovakia", code: "SK", currency: "EUR", bankAccountFormat: "SKkk BBBB BBBB CCCC CCCC CCCC" },
    { name: "Slovenia", code: "SI", currency: "EUR", bankAccountFormat: "SIkk BBSS CCCC CCCC C" },
    { name: "South Africa", code: "ZA", currency: "ZAR", bankAccountFormat: "YYYZZZZZZZZZZ" },
    { name: "South Korea", code: "KR", currency: "KRW", bankAccountFormat: "KRkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Spain", code: "ES", currency: "EUR", bankAccountFormat: "ESkk BBBB GGGG KKCC CCCC CCCC" },
    { name: "Sri Lanka", code: "LK", currency: "LKR", bankAccountFormat: "LKkk BBBB CCCC CCCC CCCC CC" },
    { name: "St. Lucia", code: "LC", currency: "XCD", bankAccountFormat: "LCkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Sweden", code: "SE", currency: "SEK", bankAccountFormat: "SEkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Switzerland", code: "CH", currency: "CHF", bankAccountFormat: "CHkk BBBB BCCC CCCC CCCC C" },
    { name: "Taiwan", code: "TW", currency: "TWD", bankAccountFormat: "TWkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Tanzania", code: "TZ", currency: "TZS", bankAccountFormat: "TZkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Thailand", code: "TH", currency: "THB", bankAccountFormat: "XXXXXXXXXYYYYYYY" },
    { name: "Trinidad & Tobago", code: "TT", currency: "TTD", bankAccountFormat: "TTkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Tunisia", code: "TN", currency: "TND", bankAccountFormat: "TNkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Turkey", code: "TR", currency: "TRY", bankAccountFormat: "TRkk BBBB CCCC CCCC CCCC CCCC CCC" },
    { name: "United Arab Emirates", code: "AE", currency: "AED", bankAccountFormat: "AEkk BBBB CCCC CCCC CCCC CCCC CCCC" },
    { name: "United Kingdom", code: "GB", currency: "GBP", bankAccountFormat: "GBkk BBBB SSSS SSCC CCCC CC" },
    { name: "United States", code: "US", currency: "USD", bankAccountFormat: "RRRRRRRRR-AAAAAAAAAA" },
    { name: "Uruguay", code: "UY", currency: "UYU", bankAccountFormat: "UYkk BBBB CCCC CCCC CCCC CCCC" },
    { name: "Uzbekistan", code: "UZ", currency: "UZS", bankAccountFormat: "UZkk BBBB CCCC CCCC CCCC CCCC C" },
    { name: "Vietnam", code: "VN", currency: "VND", bankAccountFormat: "VNkk BBBB CCCC CCCC CCCC CCCC CCCC" },
];
