import styles from './ProgrammeEvidence.module.css'
export default function PenProgramme({ school = false }) {
    return <section id="pen-programmes" className={styles.section} aria-labelledby="pen-programme-title">
        <div className={styles.penIntro}><div><p className={styles.eyebrow}>3D PEN / MAKE BY HAND</p><h2 id="pen-programme-title">Draw the pieces.<br /><em>Make a little model.</em></h2><p className={styles.intro}>Start with a template and a few lines of plastic. Join the pieces, add a support and see your flat drawing stand up. We guide the first steps, then help participants try their own details.</p></div><div className={styles.penDiagram} aria-label="Example making sequence: trace a panel, join panels, test a model"><div><span className={styles.flatShape} aria-hidden="true" /><p>Trace a panel</p></div><span aria-hidden="true">→</span><div><span className={styles.builtShape} aria-hidden="true" /><p>Join &amp; test</p></div></div></div>
        <div className={styles.cards}>
            <article className={styles.outcome}><span className={styles.tag}>SCHOOLS</span><h3>A first model to show the class</h3><p>Trace simple shapes, join them and see which connections hold. Students can add their own details and explain how they helped the model stand up.</p><div className={styles.evidence}><span>PROGRAMME GOAL</span>Turn flat pieces into a model and explain how they connect.</div></article>
            <article className={styles.outcome}><span className={styles.tag}>COMPANY TEAMS</span><h3>One model, made together</h3><p>Choose a shared idea, divide the pieces and work out how to join them. There is room to make, compare and enjoy the first attempts.</p><div className={styles.evidence}><span>PROGRAMME GOAL</span>Plan the pieces together and test the joined model.</div></article>
            <article className={styles.outcome}><span className={styles.tag}>COMMUNITY GROUPS</span><h3>Make a piece of a shared display</h3><p>Bring a theme your group cares about. We can plan a guided activity where each person makes a piece to add to the shared work.</p><div className={styles.evidence}><span>PROGRAMME GOAL</span>Make a piece, add it to the display and tell its story.</div></article>
        </div>
        <p className={styles.intro}>New to a 3D pen? That is a good place to start. Tell us the ages, group size and time available. We will suggest a suitable project and agree on the materials, equipment and supervision before the session.</p>
        <a href="#enquire" className={styles.penLink}>{school ? 'Plan a 3D pen session for your school' : 'Plan a 3D pen programme for your group'} ↗</a>
    </section>
}
