'use client'
import { useCallback, useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { workshopGroups, workshopClassroomGroupPage } from '@/lib/workshopPages'
import ReviewedGroupPage from './ReviewedGroupPage'
import { clearDraftCache } from './useVersionedDraft'
import { useClassPolling } from './useClassPolling'
import FeedbackForm from './FeedbackForm'
import RefinementForm from './RefinementForm'
import IncomingFeedback from './IncomingFeedback'
export async function classroomRequest(url, method = 'GET', body) {
    const response = await fetch(url, { method, cache: 'no-store', ...(body ? { headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : {}) })
    if (response.status === 304) return { unchanged: true }
    const result = await response.json()
    if (!response.ok) throw Object.assign(Error(result.error || 'Unable to save.'), { status: response.status, homeGroup: result.homeGroup })
    return result
}
export default function Classroom({ homeGroup = null }) {
    const [lesson, setLesson] = useState(null), [message, setMessage] = useState('Loading class access…'), [viewPhase, setViewPhase] = useState(null), [seat, setSeat] = useState('group' + (homeGroup?.slice(1) || '1') + 'student1'), [password, setPassword] = useState(''), [busy, setBusy] = useState(false), [actualHome, setActualHome] = useState(null), [reviewTarget, setReviewTarget] = useState(null)
    const refreshSequence = useRef(0), mounted = useRef(true), lessonVersion = useRef(null), lessonSeat = useRef(null)
    const refresh = useCallback(async () => {
        const sequence = ++refreshSequence.current
        try { const query = new URLSearchParams(); if (homeGroup) query.set('homeGroup', homeGroup); if (lessonVersion.current !== null) { query.set('since', lessonVersion.current); query.set('seat', lessonSeat.current || '') } const next = await classroomRequest('/api/workshop/classroom' + (query.size ? '?' + query.toString() : '')); if (!mounted.current || sequence !== refreshSequence.current) return false; if (next.unchanged) return true; lessonVersion.current = next.version; lessonSeat.current = next.seat; setLesson(next); setViewPhase(value => value || next.phase); setMessage(''); return true }
        catch (error) { if (!mounted.current || sequence !== refreshSequence.current) return; if (error.status === 401 || error.status === 403) setLesson(null); setActualHome(error.homeGroup || null); setMessage(error.message); return false }
    }, [homeGroup])
    useEffect(() => { const sequenceRef = refreshSequence; mounted.current = true; return () => { mounted.current = false; sequenceRef.current++ } }, [])
    useEffect(() => { const changed = event => { if (event.key === 'fit:class:authSignal') { lessonVersion.current = null; lessonSeat.current = null; refreshSequence.current++; clearDraftCache(); setLesson(null); setViewPhase(null); refresh() } }; window.addEventListener('storage', changed); return () => window.removeEventListener('storage', changed) }, [refresh])
    useEffect(() => { lessonVersion.current = null; lessonSeat.current = null; refreshSequence.current++; clearDraftCache(); setLesson(null); setActualHome(null); setViewPhase(null) }, [homeGroup])
    useEffect(() => { setReviewTarget(null); if (lesson?.seat) { try { const value = localStorage.getItem('fit:class:reviewTarget:' + lesson.seat); if (workshopGroups.some(group => group.id === value && group.id !== lesson.group)) setReviewTarget(value) } catch {} } }, [lesson?.seat, lesson?.group])
    useClassPolling(refresh, 'classroom:' + (homeGroup || 'entry'))
    async function login(event) { event.preventDefault(); setBusy(true); lessonVersion.current = null; lessonSeat.current = null; refreshSequence.current++; clearDraftCache(); setLesson(null); try { await classroomRequest('/api/workshop/session', 'POST', { seat, password }); setPassword(''); setViewPhase(null); try { localStorage.setItem('fit:class:authSignal', crypto.randomUUID()) } catch {} await refresh() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
    if (!lesson) return <main className="max-w-xl mx-auto p-6 py-12 ph-no-capture ph-mask"><h1 className="text-3xl">{homeGroup ? 'Home Group ' + homeGroup.slice(1) + ' classroom login' : 'Class login'}</h1><p className="mt-3">Use the temporary student login your teacher gave you. Your Tinkercad account is separate.</p><form onSubmit={login} className="mt-5"><label>Student label<input className="formInput block w-full" autoComplete="username" required value={seat} onChange={e => setSeat(e.target.value)} /></label><label className="block mt-4">Temporary password<input type="password" autoComplete="current-password" required className="formInput block w-full" value={password} onChange={e => setPassword(e.target.value)} /></label><button className="formBlackButton mt-5" disabled={busy}>{busy ? 'Signing in…' : 'Enter class'}</button></form><p role="status" className="mt-4">{message}</p>{actualHome && <Link className="underline" href={'/workshop/' + actualHome + '/classroom'}>Open my Group {actualHome.slice(1)} classroom</Link>}</main>
    if (lesson.role === 'teacher') return <main className="p-8"><h1>Teacher account</h1><a className="underline" href="/admin/workshop">Open lesson controls and live submissions</a></main>
    if (!homeGroup || lesson.group !== homeGroup) return <main className="max-w-xl mx-auto p-6 py-12"><h1>Home Group {lesson.group.slice(1)}</h1><p>Your authenticated group stays with your student account.</p><Link className="underline mt-4 inline-block" href={'/workshop/' + lesson.group + '/classroom'}>Open my Group {lesson.group.slice(1)} classroom</Link></main>
    return <main className="max-w-6xl mx-auto px-5 py-10 ph-no-capture ph-mask"><h1 className="text-3xl">Home Group {homeGroup.slice(1)}: present, give feedback, refine</h1><p className="mt-3">{lesson.seat} | Group {lesson.group.slice(1)}</p>
        <div role="status" aria-live="polite" className="border rounded-xl p-4 mt-5"><p>Teacher’s active stage: <strong>{lesson.phase}</strong>. {message}</p><p className="text-sm mt-2">Updates usually refresh about every 8 seconds. Hidden or offline tabs can take longer. Your draft text is kept while reconnecting.</p>{viewPhase !== lesson.phase && <><p>Your draft is kept. The teacher changed stages.</p><button className="formWhiteButton mt-3" onClick={() => setViewPhase(lesson.phase)}>Open active stage</button></>}</div>
        <div className="flex flex-wrap gap-3 mt-4">{['PRESENT', 'FEEDBACK', 'REFINE'].map(phase => <button key={phase} className="formWhiteButton" onClick={() => setViewPhase(phase)} aria-pressed={phase === viewPhase}>{phase}</button>)}<button className="formWhiteButton" onClick={async () => { try { await classroomRequest('/api/workshop/session', 'DELETE'); lessonVersion.current = null; lessonSeat.current = null; refreshSequence.current++; clearDraftCache(); setLesson(null); setViewPhase(null); setMessage('Signed out of the class.'); try { localStorage.setItem('fit:class:authSignal', crypto.randomUUID()) } catch {} } catch (error) { setMessage(error.message) } }}>Leave class</button></div>
        {lesson.ownClassDetails && <details className="mt-5 ph-no-capture ph-mask"><summary>Your private Tinkercad account details</summary><p>{lesson.ownClassDetails.accountLabel}</p><p className="whitespace-pre-wrap">{lesson.ownClassDetails.loginDetails}</p>{lesson.ownClassDetails.classLink?.startsWith('https://www.tinkercad.com/') && <a className="underline" href={lesson.ownClassDetails.classLink} target="_blank" rel="noreferrer">Open your assigned Tinkercad class</a>}</details>}
        {viewPhase === 'PRESENT' && <><p className="mt-6">Present both ideas, the difficulty each helps with, the mechanism and a useful improvement. Visitors listen and ask questions.</p><ReviewedGroupPage group={workshopClassroomGroupPage(homeGroup)} classroom /><details className="mt-6"><summary>Browse other groups’ public projects</summary>{workshopGroups.filter(g => g.id !== homeGroup).map(g => <Link key={g.id} className="underline block mt-2" href={'/workshop/' + g.id}>Read Group {g.id.slice(1)} project</Link>)}</details></>}
        {viewPhase === 'FEEDBACK' && lesson.assignment && <><section className="mt-6" aria-label="Outgoing peer review"><h2 className="text-2xl">Home Group {homeGroup.slice(1)}: peer feedback</h2><p className="mt-3"><strong>Assigned review: Group {lesson.assignment.target.slice(1)}</strong>. Read both ideas and answer the three questions. You may also review any other group.</p><label className="block mt-4">Review another group<select aria-label="Review another group" className="formInput block w-full" value={reviewTarget || lesson.assignment.target} onChange={event => { setReviewTarget(event.target.value); try { localStorage.setItem('fit:class:reviewTarget:' + lesson.seat, event.target.value) } catch {} }}>{workshopGroups.filter(group => group.id !== homeGroup).map(group => <option key={group.id} value={group.id}>Group {group.id.slice(1)}{group.id === lesson.assignment.target ? ' - Assigned review' : ' - Optional review'}</option>)}</select></label><p className="text-sm mt-2">You stay on your own group page. Drafts and pending submissions stay with their selected target and idea; switch back to check an earlier receipt.</p><ReviewedGroupPage key={reviewTarget || lesson.assignment.target} group={workshopClassroomGroupPage(reviewTarget || lesson.assignment.target)} classroom /><FeedbackForm key={lesson.seat + ':' + (reviewTarget || lesson.assignment.target)} group={workshopClassroomGroupPage(reviewTarget || lesson.assignment.target)} lesson={lesson} onRefresh={refresh} /></section><IncomingFeedback key={lesson.seat} lesson={lesson} /></>}
        {viewPhase === 'REFINE' && <><ReviewedGroupPage group={workshopClassroomGroupPage(lesson.group)} classroom /><RefinementForm key={lesson.seat} lesson={lesson} onRefresh={refresh} /></>}
    </main>
}
