'use client'
import { useEffect, useRef, useState } from 'react'
import { workshopGroups, workshopClassroomGroupPage } from '@/lib/workshopPages'
import ReviewedGroupPage from './ReviewedGroupPage'
import { clearDraftCache } from './useVersionedDraft'
import { useClassPolling } from './useClassPolling'
import FeedbackForm from './FeedbackForm'
import RefinementForm from './RefinementForm'
export async function classroomRequest(url, method = 'GET', body) {
    const response = await fetch(url, { method, cache: 'no-store', ...(body ? { headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : {}) })
    if (response.status === 304) return { unchanged: true }
    const result = await response.json()
    if (!response.ok) throw Object.assign(Error(result.error || 'Unable to save.'), { status: response.status })
    return result
}
export default function Classroom() {
    const [lesson, setLesson] = useState(null), [message, setMessage] = useState('Loading class access…'), [viewPhase, setViewPhase] = useState(null), [seat, setSeat] = useState('group1student1'), [password, setPassword] = useState(''), [busy, setBusy] = useState(false)
    const refreshSequence = useRef(0), mounted = useRef(true), lessonVersion = useRef(null), lessonSeat = useRef(null)
    async function refresh() {
        const sequence = ++refreshSequence.current
        try { const next = await classroomRequest('/api/workshop/classroom' + (lessonVersion.current === null ? '' : '?since=' + lessonVersion.current + '&seat=' + encodeURIComponent(lessonSeat.current || ''))); if (!mounted.current || sequence !== refreshSequence.current) return false; if (next.unchanged) return true; lessonVersion.current = next.version; lessonSeat.current = next.seat; setLesson(next); setViewPhase(value => value || next.phase); setMessage(''); return true }
        catch (error) { if (!mounted.current || sequence !== refreshSequence.current) return; if (error.status === 401 || error.status === 403) setLesson(null); setMessage(error.message); return false }
    }
    useEffect(() => { const sequenceRef = refreshSequence; mounted.current = true; return () => { mounted.current = false; sequenceRef.current++ } }, [])
    useEffect(() => { const changed = event => { if (event.key === 'fit:class:authSignal') { lessonVersion.current = null; lessonSeat.current = null; refreshSequence.current++; clearDraftCache(); setLesson(null); setViewPhase(null); refresh() } }; window.addEventListener('storage', changed); return () => window.removeEventListener('storage', changed) }, [])
    useClassPolling(refresh, 'classroom')
    async function login(event) { event.preventDefault(); setBusy(true); lessonVersion.current = null; lessonSeat.current = null; refreshSequence.current++; clearDraftCache(); setLesson(null); try { await classroomRequest('/api/workshop/session', 'POST', { seat, password }); setPassword(''); setViewPhase(null); try { localStorage.setItem('fit:class:authSignal', crypto.randomUUID()) } catch {} await refresh() } catch (error) { setMessage(error.message) } finally { setBusy(false) } }
    if (!lesson) return <main className="max-w-xl mx-auto p-6 py-12 ph-no-capture ph-mask"><h1 className="text-3xl">Workshop class login</h1><p className="mt-3">Use the temporary student login your teacher gave you. Your Tinkercad account is separate.</p><form onSubmit={login} className="mt-5"><label>Student label<input className="formInput block w-full" autoComplete="username" required value={seat} onChange={e => setSeat(e.target.value)} /></label><label className="block mt-4">Temporary password<input type="password" autoComplete="current-password" required className="formInput block w-full" value={password} onChange={e => setPassword(e.target.value)} /></label><button className="formBlackButton mt-5" disabled={busy}>{busy ? 'Signing in…' : 'Enter class'}</button></form><p role="status" className="mt-4">{message}</p></main>
    if (lesson.role === 'teacher') return <main className="p-8"><h1>Teacher account</h1><a className="underline" href="/admin/workshop">Open lesson controls and live submissions</a></main>
    return <main className="max-w-6xl mx-auto px-5 py-10 ph-no-capture ph-mask"><h1 className="text-3xl">Gallery walk: present, give feedback, refine</h1><p className="mt-3">{lesson.seat} • Group {lesson.group.slice(1)}</p>
        <div role="status" aria-live="polite" className="border rounded-xl p-4 mt-5"><p>Teacher’s active stage: <strong>{lesson.phase}</strong>. {message}</p><p className="text-sm mt-2">Updates usually refresh about every 8 seconds. Hidden or offline tabs can take longer. Your draft text is kept while reconnecting.</p>{viewPhase !== lesson.phase && <><p>Your draft is kept. The teacher changed stages.</p><button className="formWhiteButton mt-3" onClick={() => setViewPhase(lesson.phase)}>Open active stage</button></>}</div>
        <div className="flex flex-wrap gap-3 mt-4">{['PRESENT', 'FEEDBACK', 'REFINE'].map(phase => <button key={phase} className="formWhiteButton" onClick={() => setViewPhase(phase)} aria-pressed={phase === viewPhase}>{phase}</button>)}<button className="formWhiteButton" onClick={async () => { try { await classroomRequest('/api/workshop/session', 'DELETE'); lessonVersion.current = null; lessonSeat.current = null; refreshSequence.current++; clearDraftCache(); setLesson(null); setViewPhase(null); setMessage('Signed out of the class.'); try { localStorage.setItem('fit:class:authSignal', crypto.randomUUID()) } catch {} } catch (error) { setMessage(error.message) } }}>Leave class</button></div>
        {lesson.ownClassDetails && <details className="mt-5 ph-no-capture ph-mask"><summary>Your private Tinkercad account details</summary><p>{lesson.ownClassDetails.accountLabel}</p><p className="whitespace-pre-wrap">{lesson.ownClassDetails.loginDetails}</p>{lesson.ownClassDetails.classLink?.startsWith('https://www.tinkercad.com/') && <a className="underline" href={lesson.ownClassDetails.classLink} target="_blank" rel="noreferrer">Open your assigned Tinkercad class</a>}</details>}
        {viewPhase === 'PRESENT' && <><p className="mt-6">Present both ideas, the difficulty each helps with, the mechanism and a useful improvement. Visitors listen and ask questions.</p>{workshopGroups.map(g => <ReviewedGroupPage key={g.id} group={workshopClassroomGroupPage(g.id)} classroom />)}</>}
        {viewPhase === 'FEEDBACK' && lesson.assignment && <><h2 className="text-2xl mt-6">Home Group {lesson.group.slice(1)}: review Group {lesson.assignment.target.slice(1)}</h2><p className="mt-3">Round {lesson.assignment.round}. Read both ideas in your assigned group&apos;s project. Choose one idea and answer all three questions using your own account.</p><ReviewedGroupPage group={workshopClassroomGroupPage(lesson.assignment.target)} classroom /><FeedbackForm key={lesson.seat + ':' + lesson.assignment.target} group={workshopClassroomGroupPage(lesson.assignment.target)} lesson={lesson} onRefresh={refresh} /><details className="mt-6"><summary>Browse all other projects and recover earlier review drafts</summary>{workshopGroups.filter(group => group.id !== lesson.group && group.id !== lesson.assignment.target).map(group => <section key={group.id} className="mt-6"><ReviewedGroupPage group={workshopClassroomGroupPage(group.id)} classroom /><FeedbackForm key={lesson.seat + ':' + group.id} group={workshopClassroomGroupPage(group.id)} lesson={lesson} onRefresh={refresh} /></section>)}</details></>}
        {viewPhase === 'REFINE' && <><ReviewedGroupPage group={workshopClassroomGroupPage(lesson.group)} classroom /><RefinementForm key={lesson.seat} lesson={lesson} onRefresh={refresh} /></>}
    </main>
}
