'use client'
import { useState } from 'react'
import Link from 'next/link'
import { classroomRequest } from './Classroom'
import { useClassPolling } from './useClassPolling'
import WorkshopAudit from './WorkshopAudit'
import GuestTeacherResponses from './GuestTeacherResponses'
import TeacherTinkercad from './TeacherTinkercad'
import TeacherBackup from './TeacherBackup'
export default function GuestTeacherClassroom() {
    const [selectedGroup, setSelectedGroup] = useState('all'), [lesson, setLesson] = useState(null), [busy, setBusy] = useState(false), [message, setMessage] = useState('Loading teacher controls…')
    async function refresh() { try { setLesson(await classroomRequest('/api/admin/workshop/guest')); setMessage('') } catch (error) { setMessage(error.message); if ([401, 403].includes(error.status)) setLesson(null) } }
    useClassPolling(refresh, 'guest-teacher')
    async function action(input) { if (busy) return false; setBusy(true); setMessage('Saving…'); try { await classroomRequest('/api/admin/workshop/guest', 'PATCH', input); await refresh(); setMessage('Saved. Student screens update after their next refresh.'); return true } catch (error) { await refresh(); setMessage(error.message + ' Your unsaved edit is kept.'); return false } finally { setBusy(false) } }
    if (!lesson) return <main className="p-8 max-w-4xl mx-auto"><h1 className="text-3xl">Workshop teacher controls</h1><p role="status" className="mt-4">{message}</p><Link className="formWhiteButton mt-4" href="/sign-in?redirect_url=%2Fadmin%2Fworkshop">Sign in as the FIT teacher</Link></main>
    const activityNames = { PRESENT: 'Explore', FEEDBACK: 'Feedback', REFINE: 'Refine' }
    const settings = { feedbackOpen: lesson.feedbackOpen, refinementOpen: lesson.refinementOpen, showFeedback: lesson.showFeedback }
    return <main className="max-w-6xl mx-auto p-5 py-10 ph-mask ph-no-capture"><h1 className="text-3xl">Workshop student work</h1><p className="mt-3">See each student’s comments and revisions, grouped by their class group. Names are entered by students.</p><p role="status" aria-live="polite" className="mt-4">{message}</p>
        <Link href="/admin/workshop/instructions" target="_blank" rel="noopener noreferrer" className="underline text-sm">Show lesson instructions</Link>
        <section className="mt-6" aria-label="Group overview"><h2 className="text-xl font-semibold">Groups at a glance</h2><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3 mt-4">{lesson.progress.map(row => <button type="button" key={row.group} className="border rounded-xl p-4 text-left" onClick={() => { setSelectedGroup(row.group); document.getElementById('responses-title')?.scrollIntoView({ block: 'start' }) }}><strong>Group {row.group.slice(1)}</strong><p>{row.joinedSessions ?? 0} joined sessions</p><p>{row.submitted} feedback submitted</p><p>{row.refinementCount || 0} refinements submitted</p><p>{row.received} feedback received</p><p className="font-semibold mt-2">{!row.submitted && !row.refinementCount ? 'No submissions yet' : 'View submissions'}</p></button>)}</div>
        </section>
        <GuestTeacherResponses lesson={lesson} busy={busy} onAction={action} groupFilter={selectedGroup} onGroupChange={setSelectedGroup} />
        <TeacherTinkercad />
        <TeacherBackup />
        <details className="border rounded-xl p-5 mt-6"><summary className="cursor-pointer text-xl">Class settings — entry {lesson.entryOpen ? 'open' : 'closed'}, feedback {lesson.feedbackOpen ? 'open' : 'closed'}, refinement {lesson.refinementOpen ? 'open' : 'closed'}</summary>
        <section className="border rounded-xl p-5 mt-5"><h2 className="text-2xl">Student entry: {lesson.entryOpen ? 'open' : 'closed'}</h2><p className="mt-3">Open entry when students should join. Closing entry stops new sessions; it does not remove work or sign out students who have already joined.</p><button type="button" className="formWhiteButton mt-4" aria-pressed={lesson.entryOpen} disabled={busy} onClick={() => action({ action: 'entry', expectedVersion: lesson.version, entryOpen: !lesson.entryOpen })}>{lesson.entryOpen ? 'Close student entry' : 'Open student entry'}</button><Link className="formWhiteButton ml-3 mt-4" href="/workshop/entry">Open student entry page</Link></section>
        <section className="border rounded-xl p-5 mt-5"><h2 className="text-2xl">Student activity</h2><label className="block mt-3">Choose an activity<select className="formInput block" value={lesson.navigationTarget || 'FEEDBACK'} disabled={busy} onChange={event => action({ action: 'navigation', expectedVersion: lesson.version, target: event.target.value, locked: Boolean(lesson.navigationLocked) })}><option value="FEEDBACK">Feedback</option><option value="REFINE">Refine</option></select></label><button type="button" className="formWhiteButton mt-3" disabled={busy} aria-pressed={Boolean(lesson.navigationLocked)} onClick={() => action({ action: 'navigation', expectedVersion: lesson.version, target: lesson.navigationTarget || 'FEEDBACK', locked: !lesson.navigationLocked })}>{lesson.navigationLocked ? 'Unlock student activities' : 'Lock students to this activity'}</button><p className="text-sm mt-3">Changes reach students on their next automatic refresh. Their unfinished answers are kept.</p></section>
        <section className="border rounded-xl p-5 mt-5"><h2 className="text-2xl">Suggested activity: {activityNames[lesson.phase]}</h2><p className="mt-3">Students can read, give feedback and refine together. Use the independent switches below to open or close submissions and incoming feedback.</p><div className="flex flex-wrap gap-3 mt-4">{['PRESENT', 'FEEDBACK', 'REFINE'].map(phase => <button type="button" className="formWhiteButton" key={phase} disabled={busy} aria-pressed={phase === lesson.phase} onClick={() => action({ action: 'phase', expectedVersion: lesson.version, phase, ...settings })}>{activityNames[phase]}</button>)}</div><div className="flex flex-wrap gap-3 mt-4">{['feedbackOpen', 'refinementOpen', 'showFeedback'].map(key => <button type="button" key={key} className="formWhiteButton" disabled={busy} aria-pressed={Boolean(lesson[key])} onClick={() => action({ action: 'phase', expectedVersion: lesson.version, phase: lesson.phase, ...settings, [key]: !lesson[key] })}>{key === 'showFeedback' ? 'Class feedback visibility' : key === 'feedbackOpen' ? 'Feedback submissions' : 'Refinement submissions'}: {lesson[key] ? 'open' : 'closed'}</button>)}</div></section>
        <section className="border rounded-xl p-5 mt-5"><h2 className="text-2xl">Assigned review round</h2><p className="mt-3">Choose rounds 1 to 9 to visit every other group. Previous answers stay saved.</p><div className="flex flex-wrap gap-3 mt-4">{Array.from({ length: 9 }, (_, i) => i + 1).map(round => <button type="button" key={round} className="formWhiteButton" disabled={busy} aria-pressed={(lesson.reviewRound || 1) === round} onClick={() => action({ action: 'phase', expectedVersion: lesson.version, phase: lesson.phase, ...settings, reviewRound: round })}>Review round {round}</button>)}</div>{lesson.currentProjectVersion !== lesson.projectVersion && <><p className="mt-3">The project text changed. Close feedback before using the current version.</p><button type="button" className="formWhiteButton mt-3" disabled={busy || lesson.feedbackOpen} onClick={() => action({ action: 'projectVersion', expectedVersion: lesson.version })}>Use current project text</button></>}</section>
        </details>

        <details className="mt-8"><summary>Teacher audit history ({lesson.audit.length})</summary><WorkshopAudit events={lesson.audit} /></details><Link href="/admin/workshop/legacy" className="formWhiteButton mt-8">Open earlier account records and private handoff</Link>
    </main>
}
