'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { classroomRequest } from './Classroom'
const questions = { whatWorks: 'What works', question: 'Question', improvement: 'Specific improvement' }
export default function TeacherClassroom() {
    const [lesson, setLesson] = useState(null), [message, setMessage] = useState('Loading your protected classroom…'), [busy, setBusy] = useState(false), [edit, setEdit] = useState(null), [group, setGroup] = useState('all')
    const [privateRoster, setPrivateRoster] = useState(null), [rosterGroup, setRosterGroup] = useState('g1'), [rosterMessage, setRosterMessage] = useState('')
    async function refresh() { try { setLesson(await classroomRequest('/api/admin/workshop')); setMessage('') } catch (error) { setMessage(error.message); if ([401, 403].includes(error.status)) setLesson(null) } }
    useEffect(() => { refresh(); const timer = setInterval(refresh, 5000); return () => clearInterval(timer) }, [])
    async function action(input) {
        if (busy) return
        setBusy(true)
        try { await classroomRequest('/api/admin/workshop', 'PATCH', input); setEdit(null); await refresh(); setMessage('Saved. Student screens update within five seconds.') }
        catch (error) { setMessage(error.message); await refresh(); setMessage(error.message + ' Your unsaved edit is kept.') }
        finally { setBusy(false) }
    }
    async function loadPrivateRoster(event) {
        const file = event.target.files?.[0]; event.target.value = ''; if (!file) return
        try {
            if (file.size > 32000) throw Error('Choose the private FIT forty-seat login JSON file.')
            const parsed = JSON.parse(await file.text()), rows = parsed.credentials
            if (!Array.isArray(rows) || rows.length !== 40 || new Set(rows.map(row => row.seat)).size !== 40 || rows.some(row => !lesson.accounts.some(account => account._id === row.seat && account.group === row.group) || typeof row.password !== 'string' || !/^[A-Za-z0-9_-]{20,64}$/.test(row.password))) throw Error('This roster does not match the forty authorized student seats.')
            setPrivateRoster(rows.map(({ seat, group, password }) => ({ seat, group, password }))); setRosterMessage('Private roster loaded in this tab. Choose one group; clear it when finished.')
        } catch (error) { setRosterMessage(error instanceof SyntaxError ? 'Choose the private FIT login JSON file.' : error.message) }
    }
    if (!lesson) return <main className="max-w-4xl mx-auto p-8"><h1 className="text-3xl">Workshop teacher controls</h1><p role="status" className="mt-4">{message}</p><p className="mt-3">Sign in with your existing FIT admin account. Student accounts cannot open these controls.</p><Link href="/sign-in?redirect_url=%2Fadmin%2Fworkshop" className="underline">Sign in</Link></main>
    const settings = { feedbackOpen: lesson.feedbackOpen, refinementOpen: lesson.refinementOpen, showFeedback: lesson.showFeedback }
    return <main className="max-w-6xl mx-auto p-5 py-10 ph-no-capture ph-mask"><h1 className="text-3xl">Live workshop: teacher controls</h1><p className="mt-3">Updates every five seconds. Submissions are private to this classroom. Account passwords are delivered separately in your private handout.</p>
        <p role="status" aria-live="polite" className="mt-4">{message}</p>
        <section className="border rounded-xl p-5 mt-5"><h2 className="text-2xl">Active stage: {lesson.phase}</h2><div className="flex flex-wrap gap-3 mt-4">{['PRESENT', 'FEEDBACK', 'REFINE'].map(phase => <button key={phase} className="formWhiteButton" disabled={busy} aria-pressed={phase === lesson.phase} onClick={() => action({ action: 'phase', expectedVersion: lesson.version, phase, feedbackOpen: phase === 'FEEDBACK', refinementOpen: phase === 'REFINE', showFeedback: phase === 'REFINE' || lesson.showFeedback })}>{phase}</button>)}</div>
            <div className="flex flex-wrap gap-3 mt-4">{['feedbackOpen', 'refinementOpen', 'showFeedback'].map(key => <button key={key} className="formWhiteButton" disabled={busy || (key === 'feedbackOpen' && lesson.phase !== 'FEEDBACK') || (key === 'refinementOpen' && lesson.phase !== 'REFINE')} onClick={() => action({ action: 'phase', expectedVersion: lesson.version, phase: lesson.phase, ...settings, [key]: !lesson[key] })}>{key === 'showFeedback' ? 'Class feedback visibility' : key === 'feedbackOpen' ? 'Feedback submissions' : 'Refinement submissions'}: {lesson[key] ? 'open' : 'closed'}</button>)}</div>
        </section>
        <h2 className="text-2xl mt-8">Group progress</h2><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3 mt-4">{lesson.progress.map(row => <article key={row.group} className="border p-4 rounded-lg"><h3>Group {row.group.slice(1)}</h3><p>Received: {row.received}</p><p>Submitted: {row.submitted}</p><p>Refinement: {row.refinementVersion ? 'revision ' + row.refinementVersion : 'not submitted'}</p></article>)}</div>
        <h2 className="text-2xl mt-8">Student seats</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mt-4">{lesson.accounts.map(account => <article key={account._id} className="border rounded p-3"><p>{account._id} • Group {account.group.slice(1)}</p><p>{account.enabled ? 'Enabled' : 'Revoked'} • Expires {new Date(account.expiresAt).toLocaleString()}</p>{account.enabled && <button className="underline mt-2" disabled={busy} onClick={() => { if (window.confirm('Revoke only ' + account._id + '?')) action({ action: 'revoke', seat: account._id }) }}>Revoke this seat</button>}</article>)}</div>
        <section className="border rounded-xl p-5 mt-5 ph-no-capture ph-mask"><h2 className="text-2xl">Private group login handoff</h2><p className="mt-3">Load your private forty-seat login JSON from Library. It stays in this browser tab and is not uploaded. Show only the selected group’s four cards so pupils can log in; no printing is required.</p><label className="block mt-4">Load private login roster<input type="file" accept=".json,application/json" className="block mt-2" onChange={loadPrivateRoster} /></label><label className="block mt-4">Reveal one group<select className="formInput block" value={rosterGroup} onChange={e => setRosterGroup(e.target.value)}>{Array.from({ length: 10 }, (_, i) => <option key={i} value={'g' + (i + 1)}>Group {i + 1}</option>)}</select></label>
            {privateRoster && <><div aria-label="Selected group login cards" className="grid sm:grid-cols-2 gap-3 mt-4">{privateRoster.filter(row => row.group === rosterGroup).map(row => { const account = lesson.accounts.find(a => a._id === row.seat), active = account?.enabled && Date.parse(account.expiresAt) > Date.now(); return <article key={row.seat} className="border rounded p-4"><h3>{row.seat}</h3><p>Website: /workshop/classroom</p>{active ? <p>Temporary password: <code className="break-all">{row.password}</code></p> : <p>Seat revoked or expired; do not distribute this login.</p>}<p>Tinkercad is separate. Each student sees only their own assigned instructions after signing in.</p></article> })}</div><button type="button" className="formWhiteButton mt-4" onClick={() => { setPrivateRoster(null); setRosterMessage('Private passwords cleared from this tab.') }}>Clear private roster</button></>}
            <p role="status" className="mt-3">{rosterMessage}</p>
        </section>
        <h2 className="text-2xl mt-8">Feedback and moderation</h2><label className="block mt-3">Presenting group<select value={group} onChange={e => setGroup(e.target.value)} className="formInput block"><option value="all">All groups</option>{lesson.progress.map(row => <option key={row.group} value={row.group}>Group {row.group.slice(1)}</option>)}</select></label>
        {lesson.feedback.filter(row => group === 'all' || row.presentingGroup === group).map(row => <article key={row.id} className="border rounded-xl p-5 mt-4"><h3>Group {row.presentingGroup.slice(1)} • Idea {row.idea}</h3><p>From {row.seat} (Group {row.visitingGroup.slice(1)}) • {row.visibility} • Receipt {row.id}</p>{Object.entries(questions).map(([key, label]) => <p key={key} className="mt-3 whitespace-pre-wrap"><strong>{label}:</strong> {row[key]}</p>)}
            <div className="flex flex-wrap gap-3 mt-4">{['hidden', 'blocked', 'visible'].map(visibility => <button className="formWhiteButton" key={visibility} disabled={busy || row.visibility === visibility} onClick={() => action({ action: 'feedback', expectedEntryVersion: row.version, id: row.id, visibility })}>{visibility === 'visible' ? 'Restore to class' : visibility === 'hidden' ? 'Hide' : 'Block'}</button>)}<button className="formWhiteButton" onClick={() => setEdit({ id: row.id, expectedEntryVersion: row.version, visibility: row.visibility, ...Object.fromEntries(Object.keys(questions).map(key => [key, row[key]])) })}>Edit entry</button></div>
            {edit?.id === row.id && <form onSubmit={e => { e.preventDefault(); action({ action: 'feedback', expectedEntryVersion: edit.expectedEntryVersion, id: edit.id, visibility: edit.visibility, edit: Object.fromEntries(Object.keys(questions).map(key => [key, edit[key]])) }) }} className="mt-4">{Object.entries(questions).map(([key, label]) => <label className="block mt-3" key={key}>{label}<textarea aria-label={label} required maxLength={600} value={edit[key]} className="formInput block w-full" onChange={e => setEdit({ ...edit, [key]: e.target.value })} /></label>)}<button className="formBlackButton mt-3" disabled={busy}>Save teacher edit</button><button className="formWhiteButton ml-3" type="button" onClick={() => setEdit(null)}>Cancel edit</button>{edit.expectedEntryVersion !== row.version && <div className="border p-4 mt-3"><p>This entry changed. Your typed edit is kept. Compare the latest entry above before continuing.</p><button type="button" className="formWhiteButton mt-3" onClick={() => setEdit({ ...edit, expectedEntryVersion: row.version, visibility: row.visibility })}>Keep my edit and use latest entry version</button></div>}</form>}
        </article>)}
        <h2 className="text-2xl mt-8">Submitted revisions</h2>{lesson.refinements.map(row => <article className="border rounded-xl p-5 mt-4" key={row.id}><h3>Group {row.group.slice(1)} • Revision {row.version} • {row.seat}</h3>{row.ideas.map(idea => <div key={idea.idea} className="mt-3"><h4>Idea {idea.idea}</h4>{['feedbackUsed', 'change', 'reason', 'test'].map(key => <p key={key} className="whitespace-pre-wrap"><strong>{key}:</strong> {idea[key]}</p>)}</div>)}</article>)}
        <details className="mt-8"><summary>Teacher audit history ({lesson.audit.length})</summary>{lesson.audit.map((event, i) => <article key={i} className="border p-3 mt-2"><p>{event.at} • {event.actor} • {event.action} • {event.id}</p><pre className="whitespace-pre-wrap break-all">{JSON.stringify({ before: event.before, after: event.after }, null, 2)}</pre></article>)}</details>
    </main>
}
