'use client'
import { useState } from 'react'
import TeacherRevision from './TeacherRevision'
const questions = { whatWorks: 'What works', question: 'Question', improvement: 'Improvement' }
const groupName = id => 'Group ' + id.slice(1)
export default function TeacherResponses({ lesson, busy, onAction }) {
    const [target, setTarget] = useState('all'), [source, setSource] = useState('all'), [seat, setSeat] = useState('all'), [status, setStatus] = useState('visible'), [question, setQuestion] = useState('all'), [type, setType] = useState('all'), [page, setPage] = useState(0), [edit, setEdit] = useState(null)
    const all = [...lesson.feedback.map(row => ({ ...row, kind: 'feedback', target: row.presentingGroup, source: row.visitingGroup })), ...lesson.refinements.map(row => ({ ...row, kind: 'refinement', target: row.group, source: row.group }))].sort((a, b) => Date.parse(b.recordedAt) - Date.parse(a.recordedAt))
    const rows = all.filter(row => (target === 'all' || row.target === target) && (source === 'all' || row.source === source) && (seat === 'all' || row.seat === seat) && (status === 'all' || (row.visibility || 'visible') === status) && (type === 'all' || row.kind === type))
    const pages = Math.max(1, Math.ceil(rows.length / 10)), currentPage = Math.min(page, pages - 1)
    function choose(setter, value) { setter(value); setPage(0) }
    async function act(input) { if (await onAction(input)) { if (input.action === 'feedback' && input.id === edit?.id) setEdit(null); return true } return false }
    const fieldStyle = { whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', marginTop: '6px', lineHeight: 1.6 }
    return <section aria-labelledby="responses-title" className="mt-8">
        <h2 id="responses-title" className="text-2xl">Class responses</h2><p className="mt-2">{lesson.feedback.length} feedback entries · {lesson.refinements.length} revisions · {all.filter(row => row.visibility === 'hidden').length} hidden</p>
        <div className="border rounded-xl p-4 mt-4" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 180px), 1fr))', gap: '12px' }}>
            {[['Target group', target, setTarget], ['From group', source, setSource]].map(([label, value, setter]) => <label key={label}>{label}<select className="formInput block w-full" value={value} onChange={event => choose(setter, event.target.value)}><option value="all">All groups</option>{lesson.progress.map(row => <option key={row.group} value={row.group}>{groupName(row.group)}</option>)}</select></label>)}
            <label>Student seat<select className="formInput block w-full" value={seat} onChange={event => choose(setSeat, event.target.value)}><option value="all">All students</option>{lesson.accounts.map(account => <option key={account._id} value={account._id}>{account._id}</option>)}</select></label>
            <label>Status<select className="formInput block w-full" value={status} onChange={event => choose(setStatus, event.target.value)}>{[['visible', 'Visible'], ['all', 'All statuses'], ['hidden', 'Hidden'], ['blocked', 'Blocked']].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
            <label>Response type<select className="formInput block w-full" value={type} onChange={event => choose(setType, event.target.value)}><option value="all">Feedback and revisions</option><option value="feedback">Feedback</option><option value="refinement">Revisions</option></select></label>
            <label>Feedback question<select className="formInput block w-full" value={question} onChange={event => choose(setQuestion, event.target.value)}><option value="all">All questions</option>{Object.entries(questions).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
        </div>
        <p role="status" className="mt-3">{rows.length} matching responses. Showing {rows.length ? currentPage * 10 + 1 : 0}–{Math.min(rows.length, (currentPage + 1) * 10)}.</p>
        {!rows.length && <p className="border rounded-xl p-5 mt-4">No responses match these filters. Choose another group or status.</p>}
        {rows.slice(currentPage * 10, (currentPage + 1) * 10).map(row => row.kind === 'refinement' ? <div key={row.id} className="mt-4"><TeacherRevision row={row} busy={busy} onAction={act} compact /></div> : <article key={row.id} aria-label={'Feedback ' + row.id} className="border rounded-xl p-4 mt-4" style={{ overflowWrap: 'anywhere' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', flexWrap: 'wrap', gap: '8px' }}><h3 className="font-semibold">{groupName(row.presentingGroup)} · Idea {row.idea}</h3><span>{row.visibility} {row.version > 1 && '· teacher updated'}</span></div>
            <p className="text-sm mt-1">From {groupName(row.visitingGroup)} · {row.seat}</p>
            <dl className="mt-3" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 220px), 1fr))', gap: '16px' }}>{Object.entries(questions).filter(([key]) => question === 'all' || question === key).map(([key, label]) => <div key={key}><dt className="font-semibold">{label}</dt><dd style={fieldStyle}>{row[key]}</dd></div>)}</dl>
            <div className="flex flex-wrap gap-3 mt-4">{['hidden', 'blocked', 'visible'].map(visibility => <button type="button" className="formWhiteButton" key={visibility} disabled={busy || row.visibility === visibility} onClick={() => act({ action: 'feedback', expectedEntryVersion: row.version, id: row.id, visibility })}>{visibility === 'visible' ? 'Restore to class' : visibility === 'hidden' ? 'Hide' : 'Block'}</button>)}<button type="button" className="formWhiteButton" disabled={busy} onClick={() => setEdit({ id: row.id, expectedEntryVersion: row.version, visibility: row.visibility, ...Object.fromEntries(Object.keys(questions).map(key => [key, row[key]])) })}>Edit entry</button></div>
            {edit?.id === row.id && <form onSubmit={event => { event.preventDefault(); act({ action: 'feedback', expectedEntryVersion: edit.expectedEntryVersion, id: edit.id, visibility: edit.visibility, edit: Object.fromEntries(Object.keys(questions).map(key => [key, edit[key]])) }) }} className="mt-4">{Object.entries(questions).map(([key, label]) => <label className="block mt-3" key={key}>{label}<textarea aria-label={label} required maxLength={600} value={edit[key]} className="formInput block w-full" onChange={event => setEdit({ ...edit, [key]: event.target.value })} /></label>)}<button className="formBlackButton mt-3" disabled={busy}>Save teacher edit</button><button className="formWhiteButton ml-3" type="button" onClick={() => setEdit(null)}>Cancel edit</button>{edit.expectedEntryVersion !== row.version && <div className="border p-4 mt-3"><p>This entry changed. Your typed edit is kept. Compare the current text above.</p><button type="button" className="formWhiteButton mt-3" onClick={() => setEdit({ ...edit, expectedEntryVersion: row.version, visibility: row.visibility })}>Keep my edit and use latest entry version</button></div>}</form>}
            <details className="text-sm mt-3"><summary>Receipt and edit history</summary><p>Receipt {row.id} · {new Date(row.recordedAt).toLocaleString()} · Entry version {row.version}</p>{lesson.audit.filter(event => event.id === row.id).map((event, index) => <details key={index} className="mt-2"><summary>{event.action} · {new Date(event.at).toLocaleString()}</summary><pre style={fieldStyle}>{JSON.stringify({ before: event.before, after: event.after }, null, 2)}</pre></details>)}</details>
        </article>)}
        {pages > 1 && <nav aria-label="Response pages" className="flex flex-wrap gap-3 mt-4"><button type="button" className="formWhiteButton" disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}>Previous responses</button><span>Page {currentPage + 1} of {pages}</span><button type="button" className="formWhiteButton" disabled={currentPage >= pages - 1} onClick={() => setPage(currentPage + 1)}>Next responses</button></nav>}
    </section>
}
