const labels = { whatWorks: 'What works', question: 'Question', improvement: 'Improvement', feedbackUsed: 'Feedback used', change: 'Proposed change', reason: 'Reason', test: 'Next test', phase: 'Suggested activity', feedbackOpen: 'Feedback submissions', refinementOpen: 'Refinement submissions', showFeedback: 'Feedback visibility', reviewRound: 'Review round', entryOpen: 'Student entry', navigationLocked: 'Activity lock', navigationTarget: 'Chosen activity', visibility: 'Visibility', count: 'Submissions' }
const groupName = value => value?.startsWith('g') ? 'Group ' + value.slice(1) : ''
export function AuditChange({ value }) {
    if (typeof value === 'boolean') return <p>{value ? 'Open' : 'Closed'}</p>
    if (Array.isArray(value)) return value.map((row, index) => <section key={index} className="border rounded p-3 mt-2"><AuditChange value={row} /></section>)
    if (!value || typeof value !== 'object') return <p>No earlier value.</p>
    return <div>{(value.studentName || value.group || value.visitingGroup) && <p className="font-semibold">{value.studentName || 'Student'} · {groupName(value.group || value.visitingGroup)}{value.presentingGroup ? ' → ' + groupName(value.presentingGroup) : ''}</p>}<dl className="space-y-2 mt-2">{Object.entries(labels).filter(([key]) => value[key] !== undefined).map(([key, label]) => <div key={key}><dt className="font-semibold">{label}</dt><dd className="whitespace-pre-wrap break-words">{typeof value[key] === 'boolean' ? value[key] ? 'On' : 'Off' : String(value[key])}</dd></div>)}</dl>{Array.isArray(value.ideas) && value.ideas.map((idea, index) => <section key={index} className="mt-3"><h4 className="font-semibold">Idea {idea.idea || index + 1}</h4><AuditChange value={idea} /></section>)}</div>
}
const actions = { phase: 'Changed class settings', guestEntry: 'Changed student entry', feedback: 'Updated feedback', refinement: 'Updated a refinement', navigation: 'Changed the student activity lock', projectVersion: 'Updated the project reading', trashAuthor: 'Moved a student’s submissions to Trash', restoreTrashBatch: 'Restored deleted submissions' }
export default function WorkshopAudit({ events = [] }) {
    return events.map((event, index) => <details className="border rounded p-3 mt-2" key={index}><summary className="cursor-pointer">Teacher · {actions[event.action] || 'Updated a submission'} · {new Date(event.at).toLocaleString()}</summary><div className="grid md:grid-cols-2 gap-4 mt-3"><section><h4 className="font-semibold">Before</h4><AuditChange value={event.before} /></section><section><h4 className="font-semibold">After</h4><AuditChange value={event.after} /></section></div></details>)
}
