import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import BulkFilamentForm from '@/components/Shop/BulkFilamentForm'
import BulkFilamentRequests from '@/components/Admin/BulkFilamentRequests'
import { fixtureCatalogue, fixtureInput, memoryStore } from '../fixtures/bulkFilament'
import { parseBulkInput, saveBulkRequest } from '@/lib/bulkFilament'
import { BULK_CONSENT } from '@/lib/bulkFilamentConfig'
vi.mock('next/link',()=>({default:({children,...props})=><a {...props}>{children}</a>}))
const catalogue=fixtureCatalogue()
const response=(body,status=200)=>({ok:status<400,status,json:async()=>body})
beforeEach(()=>{sessionStorage.clear();vi.stubGlobal('fetch',vi.fn(async()=>response({products:catalogue,stockSource:'snapshot',checkedAt:'2026-10-09'})))})
afterEach(()=>{cleanup();vi.unstubAllGlobals()})
async function choose(colour='Black',material='PLA') {
  await screen.findByRole('button',{name:'Add colour to enquiry'})
  const p=catalogue.find(p=>p.material===material)
  fireEvent.change(screen.getByLabelText('Product / material'),{target:{value:p.id}})
  fireEvent.change(screen.getByLabelText('Colour'),{target:{value:p.types[0].options.find(o=>o.name===colour).id}})
  fireEvent.click(screen.getByRole('button',{name:'Add colour to enquiry'}))
}
async function fill() {
  await choose();fireEvent.change(screen.getByLabelText('Name'),{target:{value:'Synthetic QA'}})
  fireEvent.change(screen.getByLabelText('Email'),{target:{value:'qa@example.invalid'}})
  screen.getAllByRole('checkbox').forEach(c=>fireEvent.click(c))
}
it('shows configured ladders, optional phone and required consent',async()=>{
  render(<BulkFilamentForm/>);await choose()
  expect(screen.getByLabelText('Phone (optional)')).not.toBeRequired()
  expect(screen.getByLabelText(BULK_CONSENT)).toBeRequired()
  expect(screen.getByLabelText('Quantity line 1')).toHaveAttribute('max','14')
  expect(screen.getByText(/Inventory snapshot:/)).toBeInTheDocument()
  expect(screen.queryByText(/extra rolls/i)).not.toBeInTheDocument()
})
it.each(['Marble', 'Wood Colour'])('groups and labels %s as premium and shows the ten-roll worked example', async colour => {
  render(<BulkFilamentForm />); await choose(colour)
  const premiumGroup = screen.getByRole('group', { name: 'Lanbo Marble & Wood PLA' })
  expect(within(premiumGroup).getAllByRole('option').map(o => o.textContent)).toEqual(['Marble — 7 recorded remaining', 'Wood Colour — 11 recorded remaining'])
  expect(within(screen.getByRole('group', { name: 'Lanbo Plain PLA' })).getByRole('option', { name: /Technology Grey/ })).toBeInTheDocument()
  const premiumLine = screen.getByRole('region', { name: 'Request line 1' })
  expect(premiumLine).toHaveTextContent('Premium · Marble & Wood PLA')
  fireEvent.change(screen.getByLabelText('Quantity line 1'), { target: { value: '3' } })
  await choose('Black')
  fireEvent.change(screen.getByLabelText('Quantity line 2'), { target: { value: '7' } })
  expect(premiumLine).toHaveTextContent('10–19 (10 rolls combined)')
  expect(premiumLine).toHaveTextContent('$18.90 / roll x 3 = $56.70')
  expect(screen.getByRole('region', { name: 'Request line 2' })).toHaveTextContent('$13.90 / roll x 7 = $97.30')
  expect(screen.getByText(/Indicative total:/)).toHaveTextContent('$154.00')
})
it.each(['8', '', '0', '-1', '1.5'])('suppresses all pooled estimates for invalid Marble quantity %s and restores them after correction', async quantity => {
  render(<BulkFilamentForm />); await choose('Marble'); await choose('Black')
  fireEvent.change(screen.getByLabelText('Quantity line 2'), { target: { value: '7' } })
  const input = screen.getByLabelText('Quantity line 1')
  expect(input).toHaveAttribute('max', '7')
  fireEvent.change(input, { target: { value: quantity } })
  expect(input).toHaveAttribute('aria-invalid', 'true')
  expect(screen.getByRole('alert')).toHaveTextContent('Choose 1 to 7 rolls')
  expect(screen.queryByText(/Indicative total:/)).not.toBeInTheDocument()
  expect(screen.queryByText(/rolls combined/)).not.toBeInTheDocument()
  expect(screen.queryByText(/\/ roll x/)).not.toBeInTheDocument()
  expect(screen.getByText(/Estimate unavailable/)).toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'Send request to FIT' })).toBeDisabled()
  fireEvent.change(input, { target: { value: '3' } })
  expect(input).toHaveAttribute('aria-invalid', 'false')
  expect(screen.getByText(/Indicative total:/)).toHaveTextContent('$154.00')
  expect(screen.queryByText(/Estimate unavailable/)).not.toBeInTheDocument()
})
it('updates every PLA line when Marble crosses the mixed-colour tier; PETG is separate',async()=>{
  render(<BulkFilamentForm/>);await choose()
  fireEvent.change(screen.getByLabelText('Quantity line 1'),{target:{value:'6'}})
  await choose('Marble');fireEvent.change(screen.getByLabelText('Quantity line 2'),{target:{value:'4'}})
  await choose('Black','PETG');fireEvent.change(screen.getByLabelText('Quantity line 3'),{target:{value:'9'}})
  const regions=screen.getAllByRole('region',{name:/Request line/})
  expect(regions[0]).toHaveTextContent('10–19 (10 rolls combined)');expect(regions[0]).toHaveTextContent('83.40')
  expect(regions[1]).toHaveTextContent('18.90');expect(regions[1]).toHaveTextContent('75.60')
  expect(regions[2]).toHaveTextContent('<10 (9 rolls combined)');expect(regions[2]).toHaveTextContent('125.10')
  expect(screen.getByText(/Indicative total:/)).toHaveTextContent('284.10')
})
it.each([['Marble','PLA','8','7'],['Black','PETG','13','12']])('shows a cap error for %s %s',async(colour,material,quantity,cap)=>{
  render(<BulkFilamentForm/>);await choose(colour,material)
  fireEvent.change(screen.getByLabelText('Quantity line 1'),{target:{value:quantity}})
  expect(screen.getByRole('alert')).toHaveTextContent(`Choose 1 to ${cap} rolls`)
  expect(screen.getByRole('button',{name:'Send request to FIT'})).toBeDisabled()
})
it('does not add a duplicate selection',async()=>{
  render(<BulkFilamentForm/>);await choose();fireEvent.click(screen.getByRole('button',{name:'Add colour to enquiry'}))
  expect(screen.getByRole('alert')).toHaveTextContent('already in your request')
})
it('keeps quantities and requires review after refreshed inventory changes',async()=>{
  render(<BulkFilamentForm/>);await choose();fireEvent.change(screen.getByLabelText('Quantity line 1'),{target:{value:'6'}})
  const changed=structuredClone(catalogue);changed[0].version='a'.repeat(64);changed[0].types[0].options[0].stock=3
  fetch.mockResolvedValue(response({products:changed,stockSource:'sheet',checkedAt:'2026-10-09'}));fireEvent.focus(window)
  await screen.findByRole('button',{name:'I have reviewed the refreshed inventory'})
  expect(screen.getByLabelText('Quantity line 1')).toHaveValue(6)
  expect(screen.getByLabelText('Quantity line 1')).toHaveAttribute('max','3')
  expect(screen.getByRole('button',{name:'Send request to FIT'})).toBeDisabled()
})
it('submits without a phone and retries the exact payload after uncertain delivery',async()=>{
  render(<BulkFilamentForm/>);await fill();fetch.mockRejectedValueOnce(Error('Connection lost'))
  fireEvent.click(screen.getByRole('button',{name:'Send request to FIT'}));await screen.findByRole('button',{name:'Retry this request'})
  const first=fetch.mock.calls.at(-1)[1].body
  expect(JSON.parse(first)).toMatchObject({customer:{phone:''},consent:true})
  expect(JSON.parse(first).lines[0]).not.toHaveProperty('extraQuantity')
  expect(screen.getByLabelText('Name')).toBeDisabled()
  fetch.mockResolvedValue(response({requestId:'recovered',totalRolls:1}))
  fireEvent.click(screen.getByRole('button',{name:'Retry this request'}));await screen.findByText('recovered')
  expect(fetch.mock.calls.at(-1)[1].body).toBe(first)
  expect(screen.getByText(/No automatic email is sent to you/)).toBeInTheDocument()
})
it('shows inventory errors with a refresh action',async()=>{
  fetch.mockResolvedValue(response({error:'Inventory unavailable'},503));render(<BulkFilamentForm/>)
  expect(await screen.findByRole('alert')).toHaveTextContent('Inventory unavailable')
  expect(screen.getByRole('button',{name:'Refresh inventory'})).toBeEnabled()
})
it('admin displays the stored tier, unit price, line total and consent',async()=>{
  const store=memoryStore();await saveBulkRequest(store,parseBulkInput(fixtureInput(catalogue)),async()=>catalogue)
  fetch.mockResolvedValue(response({requests:[...store.docs.values()],next:null}))
  render(<BulkFilamentRequests/>);await screen.findByText('Synthetic QA')
  await waitFor(()=>expect(screen.getByText(/Unit price:/)).toHaveTextContent('SGD 14.90'))
  expect(screen.getByText(/Line total:/)).toHaveTextContent('SGD 29.80')
  expect(screen.getByText(/PLA band/)).toHaveTextContent('<10')
  expect(within(screen.getByRole('article')).getByText(/PDPA consent:/)).toHaveTextContent('Accepted')
})

it('requires review after the server returns changed inventory',async()=>{
  render(<BulkFilamentForm/>);await fill()
  const changed=structuredClone(catalogue);changed[0].version='a'.repeat(64)
  fetch.mockResolvedValueOnce(response({error:'Inventory changed',code:'inventory_changed'},409)).mockResolvedValueOnce(response({products:changed,checkedAt:'2026-10-09T02:00:00Z'}))
  fireEvent.click(screen.getByRole('button',{name:'Send request to FIT'}))
  await waitFor(()=>expect(screen.getByRole('button',{name:'I have reviewed the refreshed inventory'})).toBeInTheDocument())
  expect(screen.getByRole('button',{name:'Send request to FIT'})).toBeDisabled()
})

it('defaults to the first canonical product and adds another colour without changing earlier quantities',async()=>{
  render(<BulkFilamentForm/>);await screen.findByRole('button',{name:'Add colour to enquiry'})
  expect(screen.getByLabelText('Product / material')).toHaveValue(catalogue[0].id)
  fireEvent.click(screen.getByRole('button',{name:'Add colour to enquiry'}))
  fireEvent.change(screen.getByLabelText('Quantity line 1'),{target:{value:'8'}})
  fireEvent.click(screen.getByRole('button',{name:'Add another colour'}))
  expect(screen.getByLabelText('Product / material')).toHaveFocus()
  fireEvent.click(screen.getByRole('button',{name:'Add colour to enquiry'}))
  fireEvent.change(screen.getByLabelText('Quantity line 2'),{target:{value:'3'}})
  expect(screen.getByLabelText('Quantity line 1')).toHaveValue(8)
  expect(screen.getByText('Colour: White')).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button',{name:'Remove line 1'}))
  expect(screen.getAllByRole('spinbutton')).toHaveLength(1)
  expect(screen.getByLabelText('Quantity line 1')).toHaveValue(3)
})
it('submits two colours and retries the exact two-line quantity payload after a lost response',async()=>{
  render(<BulkFilamentForm/>);await fill()
  fireEvent.click(screen.getByRole('button',{name:'Add another colour'}))
  fireEvent.click(screen.getByRole('button',{name:'Add colour to enquiry'}))
  fireEvent.change(screen.getByLabelText('Quantity line 2'),{target:{value:'4'}})
  fetch.mockRejectedValueOnce(Error('Connection lost'))
  fireEvent.click(screen.getByRole('button',{name:'Send request to FIT'}));await screen.findByRole('button',{name:'Retry this request'})
  const first=fetch.mock.calls.at(-1)[1].body, input=JSON.parse(first)
  expect(input.lines.map(l=>l.quantity)).toEqual([1,4]);expect(input.lines[0]).not.toHaveProperty('extraQuantity')
  expect(input.lines[0].options).not.toEqual(input.lines[1].options)
  fetch.mockResolvedValue(response({requestId:'two-colour-recovered',totalRolls:5}))
  fireEvent.click(screen.getByRole('button',{name:'Retry this request'}));await screen.findByText('two-colour-recovered')
  expect(fetch.mock.calls.at(-1)[1].body).toBe(first)
  expect(screen.getByText('5 rolls requested')).toBeInTheDocument()
})
it.each([0,2,10])('refreshes changed stock %s on focus while preserving two colours and quantities',async stock=>{
  render(<BulkFilamentForm/>);await choose()
  fireEvent.change(screen.getByLabelText('Quantity line 1'),{target:{value:'14'}})
  fireEvent.click(screen.getByRole('button',{name:'Add another colour'}));fireEvent.click(screen.getByRole('button',{name:'Add colour to enquiry'}))
  fireEvent.change(screen.getByLabelText('Quantity line 2'),{target:{value:'3'}})
  const changed=structuredClone(catalogue);changed[0].version='a'.repeat(64);changed[0].types[0].options[0].stock=stock
  fetch.mockResolvedValue(response({products:changed,checkedAt:'2026-10-09T02:00:00Z'}))
  fireEvent.focus(window)
  await screen.findByRole('button',{name:'I have reviewed the refreshed inventory'})
  expect(screen.getByLabelText('Quantity line 1')).toHaveValue(14)
  expect(screen.getByLabelText('Quantity line 2')).toHaveValue(3)
  expect(screen.getByLabelText('Quantity line 1')).toHaveAttribute('max',String(stock))
  expect(screen.getByRole('button',{name:'Send request to FIT'})).toBeDisabled()
  expect(fetch.mock.calls.at(-1)[1]).toEqual({cache:'no-store'})
})

it('shows one quantity per colour, an enquiry notice and a privacy link',async()=>{
  render(<BulkFilamentForm/>);await choose()
  expect(screen.getAllByRole('spinbutton')).toHaveLength(1)
  expect(screen.getByText(/No payment and no stock reservation/)).toBeInTheDocument()
  expect(screen.getByLabelText(/I understand this is an enquiry for review/)).toBeRequired()
  expect(screen.getByRole('link',{name:'Privacy policy'})).toHaveAttribute('href','/privacy')
  expect(screen.queryByText(/extra rolls/i)).not.toBeInTheDocument()
})
it('renders a successful receipt without buyer email or payment promises',async()=>{
  render(<BulkFilamentForm/>);await fill()
  fetch.mockResolvedValue(response({requestId:'synthetic-reference',totalRolls:1,ownerEmailStatus:'accepted'},201))
  fireEvent.click(screen.getByRole('button',{name:'Send request to FIT'}))
  expect(await screen.findByText('synthetic-reference')).toBeInTheDocument()
  expect(screen.getByText('Your filament request is with FIT')).toBeInTheDocument()
  expect(screen.getByText(/No automatic email is sent to you/)).toBeInTheDocument()
})
it('ignores an obsolete v1 extra-roll draft rather than resending removed fields',async()=>{
  sessionStorage.setItem('fit-bulk-filament-pending-v1',JSON.stringify({input:{lines:[{recordedQuantity:2,extraQuantity:3}]}}))
  render(<BulkFilamentForm/>);await screen.findByRole('button',{name:'Add colour to enquiry'})
  expect(screen.queryByRole('button',{name:'Retry this request'})).not.toBeInTheDocument()
  expect(screen.queryByRole('spinbutton')).not.toBeInTheDocument()
})
it('recalculates pooled PLA totals on removal and submits quantities without client prices',async()=>{
  render(<BulkFilamentForm/>);await fill()
  fireEvent.change(screen.getByLabelText('Quantity line 1'),{target:{value:'4'}})
  await choose('White');fireEvent.change(screen.getByLabelText('Quantity line 2'),{target:{value:'6'}})
  expect(screen.getByText(/Indicative total:/)).toHaveTextContent('139.00')
  expect(screen.getByRole('region',{name:'Request line 1'})).toHaveTextContent('55.60')
  expect(screen.getByRole('region',{name:'Request line 2'})).toHaveTextContent('83.40')
  fireEvent.click(screen.getByRole('button',{name:'Remove line 1'}))
  expect(screen.getByText(/Indicative total:/)).toHaveTextContent('89.40')
  fetch.mockResolvedValue(response({requestId:'priced',totalRolls:6}))
  fireEvent.click(screen.getByRole('button',{name:'Send request to FIT'}));await screen.findByText('priced')
  const line=JSON.parse(fetch.mock.calls.at(-1)[1].body).lines[0]
  expect(line).not.toHaveProperty('unitCents');expect(line).not.toHaveProperty('lineCents');expect(line).not.toHaveProperty('price')
})
it('shows the base ladder estimate without a separate discount claim',async()=>{
  render(<BulkFilamentForm/>);await choose();fireEvent.change(screen.getByLabelText('Quantity line 1'),{target:{value:'3'}})
  expect(screen.getByText(/Indicative total:/)).toHaveTextContent('44.70')
  expect(screen.queryByText(/no discount|Discount:/i)).not.toBeInTheDocument()
})
