import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { act, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
const state=vi.hoisted(()=>({user:{id:'member-a'},signedIn:true,signInProps:[]}))
vi.mock('@clerk/nextjs',()=>({useUser:()=>({isLoaded:true,isSignedIn:state.signedIn,user:state.user}),SignInButton:({children,...props})=>{state.signInProps.push(props);return children}}))
vi.mock('next/link',()=>({default:({children,href,...props})=><a href={href} {...props}>{children}</a>}))
import CommunityBoard from '@/components/Community/CommunityBoard'
import CommunityThread from '@/components/Community/CommunityThread'
import CommunityEditor from '@/components/Community/CommunityEditor'
import CommunityModeration from '@/components/Community/CommunityModeration'
const id='00000000-0000-4000-8000-000000000001'
const post={entryId:id,kind:'question',parentId:null,displayName:'Maker alias',title:'A useful printing question',body:'<img src=x onerror=alert(1)> Plain maker text',topic:'3d-printing',revision:2,status:'approved',audit:[],createdAt:'2026-10-09T00:00:00.000Z'}
const response=(data,status=200)=>({ok:status<400,status,json:async()=>data})
beforeEach(()=>{state.user={id:'member-a'};state.signedIn=true;state.signInProps=[];vi.stubGlobal('fetch',vi.fn(async()=>response({items:[],nextCursor:null})));vi.stubGlobal('crypto',{randomUUID:vi.fn(()=>id)})})
afterEach(()=>vi.unstubAllGlobals())
describe('community member and moderator interactions',()=>{
  it('renders public content as text with no interpreted markup',async()=>{fetch.mockResolvedValue(response({items:[post],nextCursor:null}));const {container}=render(<CommunityBoard/>);expect(await screen.findByText(/<img src=x onerror/)).toBeInTheDocument();expect(container.querySelector('img')).toBeNull();expect(screen.getByRole('link',{name:post.title})).toHaveAttribute('href','/community/'+id)})
  it('offers explicit repair-independent sign-in and sign-up return destinations',()=>{state.user=null;state.signedIn=false;render(<CommunityBoard/>);expect(screen.getByRole('button',{name:'Sign in to post'})).toBeEnabled();expect(state.signInProps.at(-1)).toMatchObject({forceRedirectUrl:'/community',signUpForceRedirectUrl:'/community'});expect(screen.queryByRole('button',{name:'My submissions'})).not.toBeInTheDocument()})
  it('sends new content for review with a stable retry reference and keeps the draft on failure',async()=>{
    fetch.mockResolvedValueOnce(response({error:'Temporary failure'},503)).mockResolvedValueOnce(response({entry:{...post,status:'pending'}},201));const saved=vi.fn();render(<CommunityEditor onSaved={saved} onCancel={()=>{}}/>);
    fireEvent.change(screen.getByLabelText('Public maker name'),{target:{value:'Maker alias'}});fireEvent.change(screen.getByLabelText('Title'),{target:{value:post.title}});fireEvent.change(screen.getByLabelText('Your question and what you tried'),{target:{value:post.body}});fireEvent.click(screen.getByRole('checkbox'));
    fireEvent.submit(screen.getByRole('form',{name:'New community post'}));expect(await screen.findByRole('alert')).toHaveTextContent('Temporary failure');expect(screen.getByLabelText('Title')).toHaveValue(post.title);expect(saved).not.toHaveBeenCalled();
    fireEvent.submit(screen.getByRole('form',{name:'New community post'}));await waitFor(()=>expect(saved).toHaveBeenCalledOnce());const a=JSON.parse(fetch.mock.calls[0][1].body),b=JSON.parse(fetch.mock.calls[1][1].body);expect(a.clientRequestId).toBe(b.clientRequestId);expect(a).toMatchObject({guidelinesAccepted:true,displayName:'Maker alias'});expect(a).not.toHaveProperty('status');expect(a).not.toHaveProperty('ownerUserId')
  })
  it('makes an approved edit’s removal and re-review visible before saving',()=>{render(<CommunityEditor initial={post} onSaved={()=>{}} onCancel={()=>{}}/>);expect(screen.getByText(/Saving an edit removes the published version/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Save for review'})).toBeInTheDocument()})
  it('scopes private submissions to the current account and drops stale private responses',async()=>{
    const pending=[];fetch.mockImplementation(url=>url.includes('/mine')?new Promise(resolve=>pending.push(resolve)):Promise.resolve(response({items:[],nextCursor:null})));const {rerender}=render(<CommunityBoard/>);fireEvent.click(screen.getByRole('button',{name:'My submissions'}));await waitFor(()=>expect(pending).toHaveLength(1));const resolveOld=pending[0];state.user={id:'member-b'};rerender(<CommunityBoard/>);await waitFor(()=>expect(pending).toHaveLength(2));await act(async()=>{resolveOld(response({items:[{...post,title:'Member A private draft',status:'pending'}],nextCursor:null}));pending[1](response({items:[],nextCursor:null}))});expect(screen.queryByText('Member A private draft')).not.toBeInTheDocument()
  })
  it('does not withdraw until the explicit confirmation button is used',async()=>{fetch.mockImplementation((url,options)=>options?.method==='PATCH'?Promise.resolve(response({entry:{...post,status:'withdrawn'}})):Promise.resolve(response({items:[post],nextCursor:null})));render(<CommunityBoard/>);fireEvent.click(screen.getByRole('button',{name:'My submissions'}));fireEvent.click(await screen.findByRole('button',{name:'Withdraw'}));expect(fetch.mock.calls.some(([,o])=>o?.method==='PATCH')).toBe(false);fireEvent.click(screen.getByRole('button',{name:'Keep submission'}));expect(screen.queryByRole('button',{name:'Confirm withdrawal'})).not.toBeInTheDocument()})
  it('shows comment review policy and submits reports without publishing or hiding content',async()=>{
    fetch.mockImplementation((url,options)=>options?.method==='POST'?Promise.resolve(response({received:true})):Promise.resolve(response({entry:post,comments:[],nextCursor:null})));render(<CommunityThread entryId={id}/>);fireEvent.click(await screen.findByRole('button',{name:'Report this content'}));fireEvent.click(screen.getByRole('button',{name:'Send report'}));expect(await screen.findByText(/Report received for moderator review/)).toBeInTheDocument();expect(screen.getByRole('heading',{name:post.title})).toBeInTheDocument();const [,options]=fetch.mock.calls.find(([,o])=>o?.method==='POST');expect(JSON.parse(options.body)).toMatchObject({revision:2,reason:'privacy'});fireEvent.click(screen.getByRole('button',{name:'Add a comment'}));expect(screen.getByRole('form',{name:'Add a comment'})).toHaveTextContent('Every post, comment and edit is reviewed')
  })
  it('exposes moderator decisions, requires a note for rejection and sends the reviewed revision',async()=>{
    fetch.mockImplementation((url,options)=>options?.method==='POST'?Promise.resolve(response({entry:{...post,status:'approved'}})):Promise.resolve(response({items:[{...post,status:'pending',revision:1}],nextCursor:null})));render(<CommunityModeration/>);const approve=await screen.findByRole('button',{name:'Approve publication'});expect(screen.getByRole('button',{name:'Request changes'})).toBeDisabled();fireEvent.change(screen.getByLabelText('Moderation or resolution note'),{target:{value:'Please remove contact details.'}});expect(screen.getByRole('button',{name:'Request changes'})).toBeEnabled();fireEvent.click(approve);await waitFor(()=>expect(fetch.mock.calls.some(([,o])=>o?.method==='POST')).toBe(true));expect(JSON.parse(fetch.mock.calls.find(([,o])=>o?.method==='POST')[1].body)).toMatchObject({action:'approve',entryId:id,revision:1})
  })
  it('paginates with server cursors and keeps filter controls labelled',async()=>{fetch.mockResolvedValue(response({items:[post],nextCursor:'2026-10-09T00:00:00.000Z|'+id}));render(<CommunityBoard/>);fireEvent.click(await screen.findByRole('button',{name:'Older submissions'}));await waitFor(()=>expect(fetch.mock.calls.at(-1)[0]).toContain('cursor='));expect(screen.getByLabelText('Topic')).toBeInTheDocument();expect(within(screen.getByRole('group',{name:'Community views'})).getByRole('button',{name:'Questions'})).toBeInTheDocument()})
})
