import { beforeEach, describe, expect, it, vi } from 'vitest'
const h = vi.hoisted(() => ({ student: false, teacher: false, revokeAfterClaim: false, calls: [], read: vi.fn(), claim: vi.fn(), inspect: vi.fn(), importPool: vi.fn(), change: vi.fn(), teacherView: vi.fn() }))
const seat = 'guest_11111111-1111-4111-8111-111111111111'
vi.mock('@/lib/workshopGuestAccess', () => ({ requireGuestAccess: async () => { if (!h.student) throw Object.assign(Error('Session ended'), { status: 401 }); return { seat: 'guest_11111111-1111-4111-8111-111111111111', group: 'g2', role: 'student', guest: true } }, verifyGuestHome: (request, access) => { const group = new URL(request.url).searchParams.get('homeGroup'); if (group && group !== access.group) throw Object.assign(Error('Own group only'), { status: 403 }) }, requireGuestTeacher: async () => { if (!h.teacher) throw Object.assign(Error('Teacher required'), { status: 401 }); return { role: 'teacher', userId: 'example-teacher' } } }))
vi.mock('@/lib/workshopDatabase', () => ({ workshopDatabase: async () => ({ collection: () => ({ updateOne: async () => ({ modifiedCount: 1 }) }) }) }))
vi.mock('@/lib/authenticate', () => ({ UnauthorizedError: class extends Error {} }))
vi.mock('@/lib/workshopTinkercadStore', () => ({ readTinkercadAssignment: (...args) => h.read(...args), claimTinkercadAssignment: (...args) => h.claim(...args), inspectTinkercadImport: (...args) => h.inspect(...args), importTinkercadPool: (...args) => h.importPool(...args), changeTinkercadAccess: (...args) => h.change(...args), teacherTinkercadView: (...args) => h.teacherView(...args) }))
import { GET, POST } from '@/app/api/workshop/guest/tinkercad/route'
import { GET as teacherGET, PATCH } from '@/app/api/admin/workshop/tinkercad/route'
import { POST as importPOST } from '@/app/api/admin/workshop/tinkercad/import/route'
const base = 'https://www.fixitoday.com', req = (path, method = 'GET', body, origin = base) => new Request(base + path, { method, headers: { origin, ...(body ? { 'content-type': 'application/json' } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) })
beforeEach(() => { vi.clearAllMocks(); h.student = false; h.teacher = false; h.revokeAfterClaim = false; h.read.mockResolvedValue({ status: 'assigned', studentLogin: 'example-own-only', classLink: 'https://www.tinkercad.com/joinclass/EXAMPLE' }); h.claim.mockImplementation(async () => { if (h.revokeAfterClaim) h.student = false; return { status: 'assigned' } }); h.inspect.mockResolvedValue({ pool: { privateSecret: 'never-serialize' }, summary: { seats: 75, fingerprint: 'example-fingerprint' } }); h.teacherView.mockResolvedValue({ total: 75, available: 75, sessions: [] }) })
describe('protected Tinkercad HTTP routes', () => {
    it('rejects anonymous student reads and claims before touching private data', async () => { expect((await GET(req('/api/workshop/guest/tinkercad'))).status).toBe(401); expect((await POST(req('/api/workshop/guest/tinkercad', 'POST', { expectedSeat: seat }))).status).toBe(401); expect(h.read).not.toHaveBeenCalled(); expect(h.claim).not.toHaveBeenCalled() })
    it('returns private no-store headers on success and auth failure', async () => { for (const signedIn of [false, true]) { h.student = signedIn; const response = await GET(req('/api/workshop/guest/tinkercad')); expect(response.headers.get('cache-control')).toBe('private, no-store'); expect(response.headers.get('vary')).toBe('Cookie'); expect(response.headers.get('x-robots-tag')).toBe('noindex, nofollow') } })
    it('refuses another home group or an injected expected session', async () => { h.student = true; expect((await GET(req('/api/workshop/guest/tinkercad?homeGroup=g3'))).status).toBe(403); expect((await POST(req('/api/workshop/guest/tinkercad', 'POST', { expectedSeat: 'other' }))).status).toBe(403); expect((await POST(req('/api/workshop/guest/tinkercad', 'POST', { expectedSeat: seat, approved: true }))).status).toBe(403); expect(h.claim).not.toHaveBeenCalled() })
    it('rejects cross-origin claims and teacher writes', async () => { h.student = h.teacher = true; expect((await POST(req('/api/workshop/guest/tinkercad', 'POST', { expectedSeat: seat }, 'https://evil.example'))).status).toBe(403); expect((await PATCH(req('/api/admin/workshop/tinkercad', 'PATCH', {}, 'https://evil.example'))).status).toBe(403); expect((await importPOST(req('/api/admin/workshop/tinkercad/import', 'POST', { mode: 'preview' }, 'https://evil.example'))).status).toBe(403) })
    it('rechecks logged-out/revoked session after a claim before disclosing credentials', async () => { h.student = true; h.revokeAfterClaim = true; const response = await POST(req('/api/workshop/guest/tinkercad', 'POST', { expectedSeat: seat })); expect(response.status).toBe(401); expect(h.read).not.toHaveBeenCalled(); expect(await response.text()).not.toContain('example-own-only') })
    it('guest identity provides no teacher import, overview or approval access', async () => { h.student = true; expect((await teacherGET(req('/api/admin/workshop/tinkercad'))).status).toBe(401); expect((await PATCH(req('/api/admin/workshop/tinkercad', 'PATCH', {}))).status).toBe(401); expect((await importPOST(req('/api/admin/workshop/tinkercad/import', 'POST', { mode: 'preview', pool: {} }))).status).toBe(401); expect(h.inspect).not.toHaveBeenCalled(); expect(h.change).not.toHaveBeenCalled() })
    it('teacher preview returns only its safe summary, never normalized pool values', async () => { h.teacher = true; const response = await importPOST(req('/api/admin/workshop/tinkercad/import', 'POST', { mode: 'preview', pool: {} })); expect(await response.json()).toEqual({ seats: 75, fingerprint: 'example-fingerprint' }); expect(h.importPool).not.toHaveBeenCalled() })
    it('unexpected failures never echo private credentials in responses', async () => { h.teacher = true; h.inspect.mockRejectedValue(Error('example-private-login')); const response = await importPOST(req('/api/admin/workshop/tinkercad/import', 'POST', { mode: 'preview', pool: {} })); expect(response.status).toBe(503); expect(await response.text()).not.toContain('example-private-login') })
})
