import { describe, it, expect } from 'vitest'
import { randomUUID } from 'node:crypto'
import { newGuest, guestAccess, guestName, guestCookie, guestToken, requireGuestEnabled } from '@/lib/workshopGuestIdentity'
import { emptyLesson, submitClassroom, moderateClassroom, classroomView, readLesson, setGuestEntry } from '@/lib/workshopGuestClassroomStore'
import { saveWorkshopDraft, draftId } from '@/lib/workshopGuestDraftStore'
const now = new Date('2026-10-09T02:00:00Z'), teacher = { role: 'teacher', userId: 'synthetic-teacher' }
const guest = (group = 'g2', name = 'Alex') => guestAccess(newGuest(group, name, now).record, now)
function store(initial = null) { const rows = new Map(); if (initial) rows.set(initial._id, structuredClone(initial)); return { findOne: async q => rows.has(q._id) ? structuredClone(rows.get(q._id)) : null, insertOne: async row => { if (rows.has(row._id)) throw Object.assign(Error(), { code: 11000 }); rows.set(row._id, structuredClone(row)) }, replaceOne: async (q, row) => { if (rows.get(q._id)?.version !== q.version) return { modifiedCount: 0 }; rows.set(q._id, structuredClone(row)); return { modifiedCount: 1 } } } }
const open = phase => ({ ...emptyLesson(), phase, feedbackOpen: phase === 'FEEDBACK', refinementOpen: phase === 'REFINE', showFeedback: true })
const feedback = access => ({ kind: 'feedback', submissionId: randomUUID(), phaseVersion: 0, session: '2026-10-09', presentingGroup: 'g3', visitingGroup: access.group, idea: '1', whatWorks: 'The base is wide.', question: 'How does the part move?', improvement: 'Label the two parts.' })
const refinement = () => ({ kind: 'refinement', submissionId: randomUUID(), phaseVersion: 0, expectedVersion: 0, expectedEntryVersion: 0, ideas: [1, 2].map(() => ({ feedbackUsed: 'Check the joint.', change: 'Add a label.', reason: 'The sequence is clearer.', test: 'Compare two shape models.' })) })
describe('self-reported guest identities and isolated contributions', () => {
    it('makes duplicate names independent and keeps tokens outside response identity', () => { const a = newGuest('g2', 'Alex', now), b = newGuest('g2', 'Alex', now); expect(a.record.seat).not.toBe(b.record.seat); expect(a.token).not.toBe(b.token); expect(a.record._id).not.toBe(a.token); expect(guestAccess(a.record, now)).not.toHaveProperty('_id'); expect(guestAccess(a.record, now)).not.toHaveProperty('token') })
    it('validates Unicode names and group range without requiring passwords', () => { expect(guestName('  李 明  ')).toBe('李 明'); expect(guestName("O'Neil")).toBe("O'Neil"); for (const name of ['', '<script>', 'test@example.com', 'https://x.test', '\nAlex', 'x'.repeat(61)]) expect(() => guestName(name)).toThrow(); for (const group of ['g0', 'g11', 'group1']) expect(() => newGuest(group, 'Alex', now)).toThrow() })
    it('expires sessions and denies revoked identities immediately', () => { const row = newGuest('g2', 'Alex', now).record; expect(() => guestAccess({ ...row, enabled: false }, now)).toThrow(); expect(() => guestAccess(row, row.expiresAt)).toThrow(); expect(() => guestAccess({ ...row, group: 'g11' }, now)).toThrow(); expect(() => newGuest('g2', 'Alex', new Date('2026-10-11T00:00:00Z'))).toThrow(); expect(row.expiresAt.getTime() - now.getTime()).toBe(86400000) })
    it('uses a separate secure API-only cookie and can disable guest routes', () => { const a = newGuest('g2', 'Alex', now), cookie = guestCookie(a.token, a.record.expiresAt, now); for (const flag of ['HttpOnly', 'Secure', 'SameSite=Strict', 'Path=/api/workshop/guest']) expect(cookie).toContain(flag); expect(guestToken(new Request('https://x.test', { headers: { cookie } }))).toBe(a.token); expect(guestToken(new Request('https://x.test', { headers: { cookie: 'fit_workshop=' + a.token } }))).toBe(null); expect(() => requireGuestEnabled({ WORKSHOP_GUEST_ENABLED: 'false' })).toThrow() })
    it('keeps teacher entry closed by default and rejects student entry controls', async () => { const db = store(), a = guest(); expect(emptyLesson().entryOpen).toBe(false); await expect(setGuestEntry(db, a, { action: 'entry', expectedVersion: 0, entryOpen: true }, now)).rejects.toMatchObject({ status: 403 }); await setGuestEntry(db, teacher, { action: 'entry', expectedVersion: 0, entryOpen: true }, now); expect((await readLesson(db)).entryOpen).toBe(true); await expect(setGuestEntry(db, teacher, { action: 'entry', expectedVersion: 0, entryOpen: false }, now)).rejects.toMatchObject({ status: 409 }) })
    it('records two same-name authors separately and confirms each duplicate once', async () => { const a = guest(), b = guest(), db = store(open('FEEDBACK')), p = feedback(a), q = feedback(b); const x = await submitClassroom(db, a, p, now); expect(await submitClassroom(db, a, p, now)).toEqual(x); await submitClassroom(db, b, q, now); const state = await readLesson(db); expect(state.feedback).toHaveLength(2); expect(new Set(state.feedback.map(r => r.seat)).size).toBe(2); expect(state.feedback.map(r => r.studentName)).toEqual(['Alex', 'Alex']); const view = classroomView(state, guest('g3')); expect(view.feedback).toHaveLength(2); expect(JSON.stringify(view)).not.toContain('Alex'); expect(classroomView(state, guest('g4')).feedback).toHaveLength(0) })
    it('keeps two refinements additive and enforces author ownership on duplicate IDs', async () => { const a = guest(), b = guest(), db = store(open('REFINE')), p = refinement(), q = refinement(); const x = await submitClassroom(db, a, p, now); expect(await submitClassroom(db, a, p, now)).toEqual(x); await expect(submitClassroom(db, b, p, now)).rejects.toMatchObject({ status: 409 }); await submitClassroom(db, b, q, now); const view = classroomView(await readLesson(db), a); expect(view.refinements).toHaveLength(2); expect(view.refinements.every(r => !r.studentName)).toBe(true); expect(view.refinementVersion).toBe(1) })
    it('preserves moderation, hidden responses and phase gates', async () => { const a = guest(), db = store(open('FEEDBACK')), p = feedback(a); await submitClassroom(db, a, p, now); await moderateClassroom(db, teacher, { action: 'feedback', id: p.submissionId, expectedEntryVersion: 1, visibility: 'hidden' }, now); expect(classroomView(await readLesson(db), guest('g3')).feedback).toHaveLength(0); await expect(moderateClassroom(db, a, { action: 'phase' }, now)).rejects.toMatchObject({ status: 403 }); await expect(submitClassroom(store(), a, feedback(a), now)).rejects.toMatchObject({ status: 409 }) })
    it('allows both activities in PRESENT and closes each independently', async () => {
        const a = guest(), db = store();
        await moderateClassroom(db, teacher, { action: 'phase', expectedVersion: 0, phase: 'PRESENT', feedbackOpen: true, refinementOpen: true, showFeedback: true }, now);
        const state = await readLesson(db);
        expect(state).toMatchObject({ phase: 'PRESENT', feedbackOpen: true, refinementOpen: true });
        await submitClassroom(db, a, { ...feedback(a), phaseVersion: state.phaseVersion }, now);
        await submitClassroom(db, a, { ...refinement(), phaseVersion: state.phaseVersion }, now);
        const saved = await readLesson(db);
        await moderateClassroom(db, teacher, { action: 'phase', expectedVersion: saved.version, phase: 'PRESENT', feedbackOpen: false, refinementOpen: true, showFeedback: true }, now);
        const closed = await readLesson(db);
        await expect(submitClassroom(db, a, { ...feedback(a), phaseVersion: closed.phaseVersion }, now)).rejects.toMatchObject({ status: 409 });
        await submitClassroom(db, guest(), { ...refinement(), phaseVersion: closed.phaseVersion }, now);
        expect(classroomView(await readLesson(db), guest('g3')).feedback).toHaveLength(1);
    })
    it('keeps guest drafts isolated with eight snapshots, retry receipts and CAS', async () => { const a = guest(), b = guest(), db = store(), topic = 'feedback-g3-idea1'; const p = { seat: a.seat, topic, requestId: randomUUID(), expectedVersion: 0, content: { idea: '1', whatWorks: 'First text', question: '', improvement: '' } }; await saveWorkshopDraft(db, a, p, now); expect(await saveWorkshopDraft(db, a, p, now)).toMatchObject({ version: 1, unchanged: true }); await expect(saveWorkshopDraft(db, b, p, now)).rejects.toMatchObject({ status: 403 }); for (let n = 1; n < 10; n++) await saveWorkshopDraft(db, a, { ...p, expectedVersion: n, requestId: randomUUID(), content: { ...p.content, whatWorks: 'Text ' + n } }, now); expect((await db.findOne({ _id: draftId(a.seat, topic) })).snapshots).toHaveLength(8); expect(await db.findOne({ _id: draftId(b.seat, topic) })).toBe(null); await expect(saveWorkshopDraft(db, a, { ...p, requestId: randomUUID() }, now)).rejects.toMatchObject({ status: 409 }) })
})
