import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
const h = vi.hoisted(() => ({ replace: vi.fn(), fetch: vi.fn(), poll: null, lesson: null, entryOpen: true }))
vi.mock('next/navigation', () => ({ useRouter: () => ({ replace: h.replace }) }))
vi.mock('next/link', () => ({ default: ({ href, children, ...props }) => <a href={href} {...props}>{children}</a> }))
vi.mock('next/image', () => ({ default: () => null }))
vi.mock('@/components/Workshop/useClassPolling', async () => { const { useEffect, useRef } = await import('react'); return { useClassPolling: callback => { const initial = useRef(callback); h.poll = callback; useEffect(() => { initial.current() }, []) } } })
import GuestClassroom from '@/components/Workshop/GuestClassroom'
import GuestTeacherClassroom from '@/components/Workshop/GuestTeacherClassroom'
const seat = 'guest_3460d8e9-6b20-4381-bda0-39c7b286544d'
const lesson = () => ({ role: 'student', guest: true, selfReported: true, seat, studentName: 'Alex', group: 'g2', phase: 'PRESENT', phaseVersion: 0, version: 1, assignment: { target: 'g3', round: 1 }, feedback: [], refinements: [], feedbackOpen: false, refinementOpen: false, showFeedback: false })
const response = (value, status = 200) => ({ ok: status < 400, status, json: async () => value })
beforeEach(() => { h.lesson = null; h.entryOpen = true; h.replace.mockReset(); localStorage.clear(); vi.stubGlobal('fetch', h.fetch); h.fetch.mockReset(); h.fetch.mockImplementation(async url => String(url).includes('/session') ? response({ entryOpen: h.entryOpen }) : h.lesson ? response(h.lesson) : response({ error: 'Choose your group and enter your name.' }, 401)) })
afterEach(() => { cleanup(); vi.unstubAllGlobals(); localStorage.clear() })
describe('name and group entry with confirmed states', () => {
    it('shows only name, ten groups and one entry button; waits for server confirmation', async () => {
        let resolve; const entering = new Promise(done => { resolve = done })
        h.fetch.mockImplementation(async (url, options = {}) => { if (options.method === 'POST') { await entering; h.lesson = lesson(); return response({ seat, name: 'Alex', group: 'g2' }) } return String(url).includes('/session') ? response({ entryOpen: true }) : h.lesson ? response(h.lesson) : response({ error: 'Enter your name.' }, 401) })
        render(<GuestClassroom />); await waitFor(() => expect(screen.getByRole('button', { name: 'Enter workshop' })).toBeEnabled())
        expect(screen.getByLabelText('Your name')).toBeInTheDocument(); expect(screen.getByRole('combobox', { name: 'Your group' }).options).toHaveLength(10); expect(screen.queryByLabelText(/password|student label/i)).not.toBeInTheDocument()
        fireEvent.change(screen.getByLabelText('Your name'), { target: { value: 'Alex' } }); fireEvent.change(screen.getByLabelText('Your group'), { target: { value: 'g2' } }); fireEvent.click(screen.getByRole('button', { name: 'Enter workshop' })); expect(screen.getByRole('button', { name: 'Entering…' })).toBeDisabled(); expect(screen.queryByRole('heading', { name: 'Group 2 workshop' })).not.toBeInTheDocument()
        await act(async () => { resolve() }); expect(await screen.findByRole('heading', { name: 'Group 2 workshop' })).toBeInTheDocument(); expect(screen.getByText(/Alex \(self-reported\)/)).toBeInTheDocument(); expect(h.replace).toHaveBeenCalledWith('/workshop/g2/classroom')
        const call = h.fetch.mock.calls.find(([, options]) => options?.method === 'POST'); expect(JSON.parse(call[1].body)).toEqual({ name: 'Alex', group: 'g2' })
    })
    it('retains an existing browser identity after refresh without returning private details', async () => { h.lesson = { ...lesson(), ownClassDetails: { loginDetails: 'PRIVATE SENTINEL', classLink: 'PRIVATE URL' } }; render(<GuestClassroom homeGroup="g2" />); expect(await screen.findByRole('heading', { name: 'Group 2 workshop' })).toBeInTheDocument(); expect(screen.queryByText(/PRIVATE/)).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: 'PRESENT', exact: true })).toHaveAttribute('aria-pressed', 'true'); fireEvent.click(screen.getByRole('button', { name: 'FEEDBACK', exact: true })); expect(screen.getByRole('button', { name: 'FEEDBACK', exact: true })).toHaveAttribute('aria-pressed', 'true') })
    it('keeps entry closed and shows a failed entry without false success', async () => { h.entryOpen = false; render(<GuestClassroom />); expect(await screen.findByText('Your teacher has not opened entry yet.')).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Enter workshop' })).toBeDisabled(); cleanup(); h.entryOpen = true; h.fetch.mockImplementation(async (url, options = {}) => options.method === 'POST' ? response({ error: 'Entry just closed.' }, 409) : String(url).includes('/session') ? response({ entryOpen: true }) : response({ error: 'Enter your name.' }, 401)); render(<GuestClassroom />); await waitFor(() => expect(screen.getByRole('button', { name: 'Enter workshop' })).toBeEnabled()); fireEvent.change(screen.getByLabelText('Your name'), { target: { value: 'Alex' } }); fireEvent.click(screen.getByRole('button', { name: 'Enter workshop' })); expect(await screen.findByText('Entry just closed.')).toBeInTheDocument(); expect(screen.queryByRole('heading', { name: 'Group 2 workshop' })).not.toBeInTheDocument() })
    it('shows teacher saving then saved only after the server, and surfaces a rejected save', async () => {
        let resolve, reject, state = { ...lesson(), role: 'teacher', entryOpen: false, reviewRound: 1, projectVersion: 'same', currentProjectVersion: 'same', progress: [], audit: [] }; let first = true
        h.fetch.mockImplementation(async (url, options = {}) => { if (options.method === 'PATCH') { await new Promise((done, fail) => { resolve = done; reject = fail }); if (first) { state = { ...state, entryOpen: true, version: 2 }; first = false; return response({ saved: true }) } } return response(state) })
        render(<GuestTeacherClassroom />); const open = await screen.findByRole('button', { name: 'Open student entry' }); fireEvent.click(open); expect(screen.getByText('Saving…')).toBeInTheDocument(); expect(open).toBeDisabled(); expect(screen.queryByText(/^Saved\./)).not.toBeInTheDocument(); await act(async () => { resolve() }); expect(await screen.findByText(/^Saved\./)).toBeInTheDocument(); const close = screen.getByRole('button', { name: 'Close student entry' }); expect(close).toHaveAttribute('aria-pressed', 'true'); fireEvent.click(close); await act(async () => { reject(Error('Save rejected')) }); expect(await screen.findByText('Save rejected Your unsaved edit is kept.')).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Close student entry' })).toBeInTheDocument()
    })
})
