import { afterEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import GroupedTeacherResponses from '@/components/Workshop/GroupedTeacherResponses'
import { groupTeacherWork, teacherWork } from '@/lib/workshopTeacherView'

const feedback = (overrides = {}) => ({ id: 'receipt-a', seat: 'guest-private-a', studentName: 'Aisha', visitingGroup: 'g2', presentingGroup: 'g3', idea: '1', whatWorks: 'Easy to hold', question: 'Will it stay dry?', improvement: 'Add a lid', visibility: 'visible', version: 2, recordedAt: '2026-10-09T01:00:00Z', ...overrides })
const revision = (overrides = {}) => ({ id: 'revision-a', seat: 'guest-private-a', studentName: 'Aisha', group: 'g2', version: 5, authorVersion: 2, entryVersion: 3, visibility: 'visible', recordedAt: '2026-10-09T02:00:00Z', ideas: ['1', '2'].map(idea => ({ idea, feedbackUsed: 'Keep it dry', change: 'Cover ' + idea, reason: 'Protect the parts', test: 'Try some water' })), ...overrides })
const lesson = (overrides = {}) => ({ feedback: [feedback()], refinements: [revision()], progress: [{ group: 'g2' }, { group: 'g3' }], audit: [], ...overrides })
afterEach(cleanup)

describe('grouped teacher work', () => {
    it('groups all work by the student group, retaining more than ten entries and natural group order', () => {
        const data = lesson({ feedback: Array.from({ length: 12 }, (_, i) => feedback({ id: 'receipt-' + i, visitingGroup: i === 11 ? 'g10' : 'g2' })) })
        render(<GroupedTeacherResponses lesson={data} onAction={vi.fn()} />)
        expect(screen.getAllByRole('article')).toHaveLength(13)
        expect(screen.getByText('13 submissions · 2 students with work · 2 groups')).toBeInTheDocument()
        expect(screen.getAllByRole('heading', { level: 3 }).map(item => item.textContent)).toEqual(['Group 212 submissions · Collapse', 'Group 101 submission · Collapse'])
        expect(screen.getByRole('heading', { name: 'Aisha · Group 2' })).toBeInTheDocument()
        expect(screen.getByText('Cover 1')).toBeVisible()
        expect(screen.queryByRole('navigation', { name: 'Response pages' })).not.toBeInTheDocument()
        for (const item of screen.getAllByText(/guest-private-a|Receipt:/)) expect(item.closest('details')).not.toHaveAttribute('open')
        for (const button of screen.getAllByRole('button', { name: 'Edit submission' })) expect(button.closest('details')).not.toHaveAttribute('open')
    })
    it('keeps duplicate names separate, even after filtering, and never invents a missing name', () => {
        const all = teacherWork(lesson({ feedback: [feedback(), feedback({ id: 'receipt-b', seat: 'guest-private-b' }), feedback({ id: 'receipt-c', seat: 'guest-private-c', studentName: '' })] }))
        const groups = groupTeacherWork(all)
        expect(groups[0].students.map(student => student.name)).toEqual(['Aisha (1)', 'Aisha (2)', 'Name unavailable'])
        expect(groups[0].students[0].rows).toHaveLength(2)
        expect(groupTeacherWork(all, { search: 'Add a lid' })[0].students[1].name).toBe('Aisha (2)')
    })
    it('uses available account names for older records without exposing seat IDs', () => {
        const rows = teacherWork(lesson({ feedback: [feedback({ studentName: undefined })], refinements: [], accounts: [{ _id: 'guest-private-a', name: 'Nur', group: 'g2' }] }))
        expect(rows[0].nameLabel).toBe('Nur')
    })
    it('searches comments, switches to receiving group, clears filters and expands or collapses all', () => {
        render(<GroupedTeacherResponses lesson={lesson()} onAction={vi.fn()} />)
        fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'water' } })
        expect(screen.getAllByRole('article')).toHaveLength(1)
        fireEvent.click(screen.getByRole('button', { name: 'Clear filters' }))
        fireEvent.change(screen.getByLabelText('Organise by'), { target: { value: 'target' } })
        const target = screen.getByRole('region', { name: 'Group 3 work' })
        expect(within(target).getByText('Easy to hold')).toBeVisible()
        expect(within(target).getByRole('heading', { name: 'Aisha · Group 2' })).toBeInTheDocument()
        fireEvent.change(screen.getByLabelText('Group', { exact: true }), { target: { value: 'g3' } })
        expect(screen.getAllByRole('article')).toHaveLength(1)
        fireEvent.click(screen.getByRole('button', { name: 'Collapse all' }))
        expect(screen.queryByRole('article')).not.toBeInTheDocument()
        fireEvent.click(screen.getByRole('button', { name: 'Expand all' }))
        expect(screen.getAllByRole('article')).toHaveLength(1)
    })
    it('includes hidden and blocked work by default with clear labels and optional filters', () => {
        render(<GroupedTeacherResponses lesson={lesson({ feedback: [feedback({ visibility: 'hidden' })], refinements: [revision({ visibility: 'blocked' })] })} onAction={vi.fn()} />)
        expect(screen.getByText('Hidden from students', { selector: 'span' })).toBeVisible()
        expect(screen.getByText('Blocked from students', { selector: 'span' })).toBeVisible()
        fireEvent.click(screen.getByText('More filters'))
        fireEvent.change(screen.getByLabelText('Visibility'), { target: { value: 'visible' } })
        expect(screen.getByText(/No work matches/)).toBeVisible()
        expect(screen.getByText('More filters · filters active')).toBeVisible()
    })
    it('preserves the exact ID/version for moderation and a typed edit across polling conflicts', async () => {
        const action = vi.fn().mockResolvedValue(false)
        const { rerender } = render(<GroupedTeacherResponses lesson={lesson({ refinements: [] })} onAction={action} />)
        fireEvent.click(screen.getByText('Manage submission'))
        fireEvent.click(screen.getByRole('button', { name: 'Hide from students' }))
        expect(action).toHaveBeenLastCalledWith({ action: 'feedback', id: 'receipt-a', expectedEntryVersion: 2, visibility: 'hidden' })
        fireEvent.click(screen.getByRole('button', { name: 'Edit submission' }))
        fireEvent.change(screen.getByLabelText('Improvement'), { target: { value: 'Teacher edit' } })
        rerender(<GroupedTeacherResponses lesson={lesson({ feedback: [feedback({ version: 3 })], refinements: [] })} onAction={action} />)
        expect(screen.getByLabelText('Improvement')).toHaveValue('Teacher edit')
        expect(screen.getByText(/This submission changed/)).toBeVisible()
        fireEvent.click(screen.getByRole('button', { name: 'Save changes' }))
        expect(action).toHaveBeenLastCalledWith(expect.objectContaining({ expectedEntryVersion: 2, edit: expect.objectContaining({ improvement: 'Teacher edit' }) }))
        fireEvent.click(screen.getByRole('button', { name: 'Keep my edit and use latest version' }))
        fireEvent.click(screen.getByRole('button', { name: 'Save changes' }))
        expect(action).toHaveBeenLastCalledWith(expect.objectContaining({ expectedEntryVersion: 3 }))
        expect(screen.getByLabelText('Improvement')).toHaveValue('Teacher edit')
    })
    it('edits both revision ideas using entryVersion rather than the student revision count', async () => {
        const action = vi.fn().mockResolvedValue(true)
        render(<GroupedTeacherResponses lesson={lesson({ feedback: [] })} onAction={action} />)
        fireEvent.click(screen.getByText('Manage submission'))
        fireEvent.click(screen.getByRole('button', { name: 'Edit submission' }))
        fireEvent.change(screen.getAllByLabelText('Proposed change')[1], { target: { value: 'A stronger cover' } })
        fireEvent.click(screen.getByRole('button', { name: 'Save changes' }))
        expect(action).toHaveBeenCalledWith({ action: 'refinement', id: 'revision-a', expectedEntryVersion: 3, visibility: 'visible', edit: { ideas: [expect.objectContaining({ change: 'Cover 1' }), expect.objectContaining({ change: 'A stronger cover' })] } })
        expect(await screen.findByRole('button', { name: 'Edit submission' })).toBeEnabled()
        expect(screen.queryByRole('form')).not.toBeInTheDocument()
    })
    it('keeps controls disabled while saving and shows new submissions after refresh', () => {
        const data = lesson({ refinements: [] })
        const { rerender } = render(<GroupedTeacherResponses lesson={data} busy onAction={vi.fn()} />)
        fireEvent.click(screen.getByText('Manage submission'))
        expect(screen.getByRole('button', { name: 'Hide from students' })).toBeDisabled()
        rerender(<GroupedTeacherResponses lesson={{ ...data, feedback: [...data.feedback, feedback({ id: 'new', studentName: 'Ben', seat: 'guest-b' })] }} onAction={vi.fn()} />)
        expect(screen.getByRole('heading', { name: 'Ben · Group 2' })).toBeInTheDocument()
        expect(screen.getAllByRole('article')).toHaveLength(2)
    })
})
