import { act, render, screen } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
const h = vi.hoisted(() => ({ api: vi.fn(), refresh: null }))
vi.mock('@/components/Workshop/Classroom', () => ({ classroomRequest: (...args) => h.api(...args) }))
vi.mock('@/components/Workshop/useClassPolling', () => ({ useClassPolling: refresh => { h.refresh = refresh } }))
import GuestTinkercad from '@/components/Workshop/GuestTinkercad'
const seat = 'guest_11111111-1111-4111-8111-111111111111', assigned = { status: 'assigned', studentLogin: 'example-only', classLink: 'https://www.tinkercad.com/joinclass/EXAMPLE-ONLY' }
beforeEach(() => { h.api.mockReset(); h.refresh = null })
const start = async () => { render(<GuestTinkercad seat={seat} group="g2" />); await act(async () => { await h.refresh() }) }
describe('private student Tinkercad panel', () => {
    it.each(['not-ready','awaiting-approval','paused','exhausted'])('shows %s without exposing credentials or a class link', async status => { h.api.mockResolvedValue({ status }); await start(); expect(screen.queryByLabelText('Student login')).not.toBeInTheDocument(); expect(screen.queryByRole('link', { name: 'Open Tinkercad' })).not.toBeInTheDocument(); expect(screen.getByRole('status')).not.toHaveTextContent('Checking') })
    it('claims only the current approved session and displays the exact slide labels', async () => { h.api.mockResolvedValueOnce({ status: 'ready' }).mockResolvedValueOnce(assigned); await start(); expect(h.api).toHaveBeenNthCalledWith(2, '/api/workshop/guest/tinkercad?homeGroup=g2', 'POST', { expectedSeat: seat }); expect(screen.getByLabelText('Student login')).toHaveValue('example-only'); expect(screen.getByLabelText('Student login')).toHaveAttribute('readonly'); expect(screen.getByLabelText('Class ID')).toHaveValue('EXAMPLE-ONLY'); expect(screen.queryByText('This example is not a real login')).not.toBeInTheDocument(); expect(screen.getByRole('link', { name: 'Open Tinkercad' })).toHaveAttribute('rel', 'noopener noreferrer') })
    it('reads an existing assignment without consuming another seat', async () => { h.api.mockResolvedValue(assigned); await start(); await act(async () => { await h.refresh() }); expect(h.api).toHaveBeenCalledTimes(2); expect(h.api.mock.calls.every(row => row.length === 1)).toBe(true) })
    it('removes displayed credentials after revocation or expiry', async () => { h.api.mockResolvedValueOnce(assigned).mockResolvedValueOnce({ status: 'awaiting-approval' }); await start(); expect(screen.getByLabelText('Student login')).toHaveValue('example-only'); await act(async () => { await h.refresh() }); expect(screen.queryByLabelText('Student login')).not.toBeInTheDocument(); h.api.mockRejectedValueOnce(Object.assign(Error('Session ended'), { status: 401 })); await act(async () => { await h.refresh() }); expect(screen.getByRole('status')).toHaveTextContent('Session ended') })
    it('clears credentials when a refresh cannot verify current access', async () => { h.api.mockResolvedValueOnce(assigned).mockRejectedValueOnce(Error('Offline')); await start(); await act(async () => { await h.refresh() }); expect(screen.queryByLabelText('Student login')).not.toBeInTheDocument(); expect(screen.queryByRole('link')).not.toBeInTheDocument() })
    it('does not render an unsafe class URL', async () => { h.api.mockResolvedValue({ ...assigned, classLink: 'javascript:alert(1)' }); await start(); expect(screen.queryByRole('link')).not.toBeInTheDocument(); expect(screen.getByRole('status')).toHaveTextContent('check the class link') })
    it('does not use late responses from a discarded session', async () => { let resolve; h.api.mockImplementation(() => new Promise(r => { resolve = r })); const view = render(<GuestTinkercad seat={seat} group="g2" />); let pending; act(() => { pending = h.refresh() }); view.unmount(); await act(async () => { resolve(assigned); await pending }); expect(screen.queryByLabelText('Student login')).not.toBeInTheDocument() })
})
